// Writes a generated template module under packages/engine-core/templates/ (brief §8: first line NOTICE-ID).
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

export interface TemplateItem {
  id: string;
  fdomHz: number;
  b64: string;
}

export function writeTemplateModule(path: string, o: { noticeId: string; attribution: string[]; generator: string; constName: string; scaleName: string; scale: number; items: TemplateItem[] }): void {
  const lines = [
    `// NOTICE-ID: ${o.noticeId}`,
    ...o.attribution.map((l) => `// ${l}`),
    `// Generated by ${o.generator} — do not edit. Int16 little-endian, 500 Hz, unit RMS × ${o.scale}, base64.`,
    `export const ${o.scaleName} = ${o.scale};`,
    `export const ${o.constName}: ReadonlyArray<{ id: string; fdomHz: number; b64: string }> = [`,
    ...o.items.map((t) => `  { id: '${t.id}', fdomHz: ${t.fdomHz.toFixed(3)}, b64: '${t.b64}' },`),
    '];',
    '',
  ];
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, lines.join('\n'));
}
