// Lung pathology catalogue as DATA (R36/R37; stage-7-lung-pathology-catalogue.md §1–§33, Q65–Q95).
// Generated by hand from the catalogue tables; every effect carries its provenance (catalogue section, source, tag, Q).
// Severity 0–1 (graded conditions map their grades onto severity knots). Effects are applied by
// packages/engine-core/src/l2/lung/conditions.ts with the §33 stacking rule (Q93): 'mul' multiply, 'add' add
// (shunt capped 0.6, atel 0.7), 'set' take the largest departure from the healthy default.
// Pattern (piecewise-linear severity knots) borrowed from Pulse's disease severity tables (audit borrow #9, NOTICES).
export type Knots = readonly (readonly [number, number])[];
export type EffectKey =
  | 'crs' | 'raw' | 'rawExp' | 'fSlow' | 'tauSlowS' | 'atel' | 'consol' | 'recruitFrac' | 'pOpen' | 'tauRecS'
  | 'extraShunt' | 'vqLow' | 'vdAlv' | 'dlFactor' | 'hpv' | 'evlwi' | 'ccw' | 'frc' | 'pvr' | 'tIt' | 'pPtx'
  | 'leakFrac' | 'co2Slope' | 'pMax' | 'perfShare';
export type Tag = 'P' | 'TXT' | 'ENG' | 'VERIFY';
export interface Effect {
  key: EffectKey;
  op: 'mul' | 'add' | 'set';
  /** number = value at severity 1 (mul: 1 + (v − 1)·s; add: v·s; set: default + (v − default)·s), or knots [severity, value]. */
  v: number | Knots;
  /** 'affected' = only the condition's side (unilateral conditions); 'both' = both lungs (default). */
  where?: 'affected' | 'both';
  src: string; // "§5 row 'Expiratory/inspiratory R ratio': Pulse targets Rexp/Rinsp 1.5 (Officer 1998)"
  tag: Tag;
  q?: string; // e.g. 'Q73'
}
export interface Grade { name: string; severity: number }
export interface Bands {
  /** Reference: passive, intubated adult PBW 70 kg, VC VT 490 mL, RR 14, PEEP 5, 60 L/min, pause 0.3 s, FiO2 0.4, at `refSeverity`. */
  refSeverity: number;
  crs?: readonly [number, number]; // static respiratory-system compliance, mL/cmH2O
  rInsp?: readonly [number, number]; // cmH2O·s/L incl. 8.0 ETT
  autoPeep?: readonly [number, number]; // cmH2O
  plateau?: readonly [number, number];
  drivingPressure?: readonly [number, number];
  alphaDeg?: readonly [number, number]; // capnogram alpha angle
  gapPaEt?: readonly [number, number]; // PaCO2 − EtCO2 mmHg
  shunt?: readonly [number, number]; // true shunt fraction of CO
  spo2Fio2_021?: readonly [number, number];
  spo2Fio2_04?: readonly [number, number];
  spo2Fio2_10?: readonly [number, number];
  /** SpO2 change for PEEP 5 → 15: 'up' (recruits), 'none', 'down' (over-distension/haemodynamic). */
  peep5to15?: 'up' | 'none' | 'down';
  src: string;
}
export interface LungConditionData {
  id: string; // catalogue condition id, verbatim (e.g. 'copd', 'ards', 'olv', 'ptxSimple')
  label: string;
  section: number; // catalogue § number
  sided: boolean; // true when the condition acts on one lung (side chosen at apply time)
  defaultSide?: 'L' | 'R';
  /** Airway configuration set by the condition (OLV: the non-ventilated side is blocked; endobronchial: the non-intubated side). */
  mainstem?: 'blockAffected';
  grades?: readonly Grade[];
  effects: readonly Effect[];
  bands: Bands;
  /** Which sub-stage makes each part act (catalogue "When each part is wired"). */
  needs: readonly ('7a' | '7b' | '7f' | 'V')[];
  pitfall: string; // the first teaching pitfall, one sentence, paraphrased
}
export const HEALTHY = {
  crs: 55, raw: 10, rawExp: 1.2, fSlow: 0, tauSlowS: 0.5, atel: 0, consol: 0, recruitFrac: 1, pOpen: 40, tauRecS: 2.6,
  extraShunt: 0, vqLow: 0.02, vdAlv: 0.075, dlFactor: 1, hpv: 0.5, evlwi: 7, ccw: 200, frc: 1, pvr: 1, tIt: 0.4, pPtx: 0,
  leakFrac: 0, co2Slope: 1, pMax: 1, perfShare: 1,
} as const;
export const LUNG_CONDITIONS: readonly LungConditionData[] = [
  // ── §1 Pulmonary hypertension ─────────────────────────────────────────────────────────────
  {
    id: 'ph',
    label: 'Pulmonary hypertension (group 1 default) / RV failure under PPV',
    section: 1,
    sided: false,
    grades: [{ name: 'mild', severity: 0.33 }, { name: 'moderate', severity: 0.67 }, { name: 'severe', severity: 1 }],
    effects: [
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.33, 1.76], [0.67, 2.94], [1, 5.88]], src: "main §1.5 'ph': PVR 3/5/10 WU ÷ normal 1.7 WU (main §2.2 PVR row) [ENG conversion]; ESC/ERS 2022", tag: 'TXT', q: 'Q23' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.33, 0.05], [1, 0.05]], src: "§1 row 'Alveolar dead space': group 1 +0.05 VD/VT (group 4 via peFrac); grade-independent from mild [ENG]", tag: 'ENG' },
      { key: 'dlFactor', op: 'mul', v: [[0, 1], [0.33, 0.7], [1, 0.7]], src: "§1 row 'Diffusion factor': 0.7 PAH (0.5 SSc-PAH, §8); exercise/high-CO desaturation only [TXT]/[ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.67,
      alphaDeg: [100, 110],
      peep5to15: 'down',
      src: "§1 row 'Capnogram': alpha ≈105° (100–110); row 'PEEP response': PEEP > 10 cmH2O → hypotension (Miller 10e ch. 29 p. 881)",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'Permissive hypercapnia or hypoventilation raises PVR by about half while SpO2 stays normal until the RV fails; falling EtCO2 with rising PaCO2 is the tell.',
  },
  // ── §2 Acute intraoperative bronchospasm ────────────────────────────────────────────────────
  {
    id: 'bronchospasm',
    label: 'Acute intraoperative bronchospasm',
    section: 2,
    sided: false,
    effects: [
      { key: 'raw', op: 'mul', v: [[0, 1], [0.3, 1.8], [0.5, 2.8], [0.8, 4.6], [1, 6]], src: "§2 row 'Inspiratory resistance': ×(1 + 5·sev^1.5) → R 18/28/46/60 incl. ETT (main §4.3; Arnal 2018 anchor)", tag: 'ENG', q: 'Q20' },
      { key: 'rawExp', op: 'set', v: [[0, 1.2], [0.5, 1.55], [1, 1.8]], src: "§2 row 'Expiratory/inspiratory R ratio': 1.3 + 0.5·sev (1.8 at sev 1); knot 0 = healthy 1.2 [ENG]; Officer 1998 direction", tag: 'ENG', q: 'Q69' },
      { key: 'fSlow', op: 'set', v: [[0, 0], [0.3, 0.29], [0.5, 0.35], [0.8, 0.44], [1, 0.5]], src: "§2 row 'Heterogeneity (slow compartment)': fSlow 0.2 + 0.3·sev (main §4.3); knot 0 = healthy 0 [ENG]", tag: 'ENG' },
      { key: 'tauSlowS', op: 'set', v: [[0, 0.5], [0.5, 1.5], [0.8, 3], [1, 4]], src: "§2 row 'Expiratory time constant (overall)': 1.5/3/4 s at sev 0.5/0.8/1 used as τ_slow [ENG] (row 'Heterogeneity': τ_slow = 3×τ_fast)", tag: 'ENG' },
      { key: 'vqLow', op: 'add', v: 0.15, src: "§2 row 'Low-V/Q admixture': +0.05·sev … +0.15 at sev 1, FiO2-responsive (Dellinger 5e ch. 37 p. 607) [TXT]/[ENG]", tag: 'ENG' },
      { key: 'vdAlv', op: 'add', v: 0.2, src: "§2 row 'Dead space': +0.10·sev … +0.20 at sev 1 (Dellinger 5e ch. 37 p. 610) [TXT]/[ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.8,
      rInsp: [46, 46],
      autoPeep: [6, 10],
      alphaDeg: [135, 135],
      gapPaEt: [10, 20],
      peep5to15: 'down',
      src: "§2 rows 'Inspiratory resistance' (46 at 0.8), 'Auto-PEEP' (VT 500 RR 12: 6–10), 'Capnogram alpha' (135°), 'Dead space' gap 10–20, 'Recruitability' 0",
    },
    needs: ['7b', '7f', 'V'],
    pitfall: 'A flat capnogram in severe bronchospasm does not prove oesophageal intubation (nor the reverse): confirm the tube first, then treat the spasm.',
  },
  // ── §3 Asthma (chronic grades + acute severe) ────────────────────────────────────────────────
  {
    id: 'asthma',
    label: 'Asthma (chronic grades; acute severe asthma at severity 1)',
    section: 3,
    sided: false,
    grades: [
      { name: 'controlled', severity: 0.2 }, { name: 'poorly controlled', severity: 0.4 },
      { name: 'severe', severity: 0.6 }, { name: 'acute severe (asthmaAcute)', severity: 1 },
    ],
    effects: [
      { key: 'raw', op: 'mul', v: [[0, 1], [0.2, 1], [0.4, 1.3], [0.6, 1.6], [1, 4]], src: "main §1.5 'asthma' R ×1/1.3/1.6; §3 row 'Acute severe: inspiratory R' 30–50 → 40/10 = ×4 [ENG]; grade→severity map [ENG]", tag: 'ENG', q: 'Q20' },
      { key: 'rawExp', op: 'set', v: [[0, 1.2], [0.6, 1.2], [1, 1.8]], src: "§3 row 'Acute severe: expiratory R, τ': rawExpMult ×1.8 (Tuxen & Lane 1987) [ENG]; chronic grades unchanged", tag: 'ENG' },
      { key: 'fSlow', op: 'set', v: [[0, 0], [0.6, 0], [1, 0.5]], src: "§3 row 'Acute severe: expiratory R, τ': fSlow 0.5 [ENG]", tag: 'ENG' },
      { key: 'tauSlowS', op: 'set', v: [[0, 0.5], [0.6, 0.5], [1, 4]], src: "§3 row 'Acute severe: expiratory R, τ': slow τ 3–5 s → midpoint 4 [ENG]", tag: 'ENG' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.6, 1], [1, 0.75]], src: "§3 row 'Compliance': ×0.7–0.8 once hyperinflated → 0.75 [ENG]", tag: 'ENG' },
      { key: 'vqLow', op: 'add', v: [[0, 0], [0.6, 0], [1, 0.13]], src: "§3 row 'Shunt / V/Q': low V/Q 0.10–0.20 → 0.15 total − healthy 0.02 [ENG conversion] (Dellinger 5e ch. 37 p. 607)", tag: 'TXT' },
    ],
    bands: {
      refSeverity: 1,
      rInsp: [30, 50],
      alphaDeg: [135, 145],
      gapPaEt: [20, 50],
      shunt: [0, 0.05],
      spo2Fio2_021: [88, 94],
      peep5to15: 'down',
      src: "§3 rows 'Monitor signature' (alpha 135–145°, gap 20–50, SpO2 88–94 % air), 'Acute severe: inspiratory R' 30–50, 'Shunt' ≤ 0.05, 'External PEEP'",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'A "normal" PaCO2 in a breathless asthmatic is a pre-arrest sign, not reassurance.',
  },
  // ── §4 Anaphylaxis (respiratory component) ──────────────────────────────────────────────────
  {
    id: 'anaphylaxis',
    label: 'Anaphylaxis (respiratory component)',
    section: 4,
    sided: false,
    grades: [
      { name: 'I', severity: 0.2 }, { name: 'II', severity: 0.4 }, { name: 'III', severity: 0.6 },
      { name: 'IV', severity: 0.8 }, { name: 'V', severity: 1 },
    ],
    effects: [
      { key: 'raw', op: 'mul', v: [[0, 1], [0.2, 1], [0.4, 1.82], [0.6, 3.32], [0.8, 5.27], [1, 6]], src: "§4 row 'Grade → respiratory severity': bronchospasm sev 0/0.3/0.6/0.9/1 (V=arrest→1 [ENG]) through §2 R ×(1+5·sev^1.5)", tag: 'TXT', q: 'Q71' },
      { key: 'rawExp', op: 'set', v: [[0, 1.2], [0.2, 1.2], [0.4, 1.45], [0.6, 1.6], [0.8, 1.75], [1, 1.8]], src: "§4 grade→bronchospasm sev (§2 row 'Exp/insp R ratio' 1.3 + 0.5·sev) [ENG]", tag: 'ENG', q: 'Q71' },
      { key: 'fSlow', op: 'set', v: [[0, 0], [0.2, 0], [0.4, 0.29], [0.6, 0.38], [0.8, 0.47], [1, 0.5]], src: "§4 grade→bronchospasm sev (§2 row 'Heterogeneity' fSlow 0.2 + 0.3·sev) [ENG]", tag: 'ENG', q: 'Q71' },
      { key: 'vqLow', op: 'add', v: [[0, 0], [0.2, 0], [0.4, 0.045], [0.6, 0.09], [0.8, 0.135], [1, 0.15]], src: "§4 grade→bronchospasm sev (§2 row 'Low-V/Q admixture' 0.15·sev) [ENG]", tag: 'ENG', q: 'Q71' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.2, 0], [0.4, 0.06], [0.6, 0.12], [0.8, 0.18], [1, 0.2]], src: "§4 grade→bronchospasm sev (§2 row 'Dead space' 0.20·sev); low-CO dead space is emergent (§4 row 'Dead space from low CO')", tag: 'ENG', q: 'Q71' },
    ],
    bands: {
      refSeverity: 0.6,
      alphaDeg: [130, 130],
      src: "§4 row 'Capnogram shape': alpha ≈130° at grade III (bronchospasm share); EtCO2 20–25 at grade III is emergent from low CO (row 'Dead space from low CO')",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'Bronchospasm right after succinylcholine in a non-asthmatic patient is anaphylaxis until proven otherwise.',
  },
  // ── §5 COPD / emphysema by GOLD grade ─────────────────────────────────────────────────────────
  {
    id: 'copd',
    label: 'COPD / emphysema (GOLD 1–4)',
    section: 5,
    sided: false,
    grades: [{ name: 'GOLD 1', severity: 0.25 }, { name: 'GOLD 2', severity: 0.5 }, { name: 'GOLD 3', severity: 0.75 }, { name: 'GOLD 4', severity: 1 }],
    effects: [
      { key: 'raw', op: 'mul', v: [[0, 1], [0.25, 1.3], [0.5, 1.8], [0.75, 2.5], [1, 3.5]], src: "main §1.5 'copd' R ×1.3/1.8/2.5/3.5 (§5 row 'Inspiratory resistance' 13/18/25/35 incl. ETT; Arnal 22 [16–33])", tag: 'P', q: 'Q19' },
      { key: 'rawExp', op: 'set', v: [[0, 1.2], [0.25, 1.5], [0.5, 1.5], [0.75, 1.55], [1, 1.7]], src: "§5 row 'Expiratory/inspiratory R ratio': 1.5 (Pulse; Officer 1998/Farah 2009); GOLD 3 1.55, GOLD 4 1.7 (range 1.3–2.0, 'worse in emphysema') for the auto-PEEP band [ENG]", tag: 'P' },
      { key: 'fSlow', op: 'set', v: [[0, 0], [0.5, 0.4], [0.75, 0.5], [1, 0.6]], src: "main §4.3 'COPD slow compartment': GOLD 2/3/4 fSlow 0.4/0.5/0.6; GOLD 1 interpolated [ENG]", tag: 'ENG', q: 'Q19' },
      { key: 'tauSlowS', op: 'set', v: [[0, 0.5], [0.5, 1.2], [0.75, 2], [1, 3]], src: "main §4.3 'COPD slow compartment': τ_slow 1.2/2.0/3.0 s at GOLD 2/3/4; GOLD 1 interpolated [ENG]; Arnal 2018", tag: 'ENG', q: 'Q19' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.5, 1.09], [0.75, 1.24], [1, 1.36]], src: "§5 row 'Static compliance': Pulse targets 60/68/75 at GOLD 2/3/4 (Arnal 59 [43–75]); 7b prototype: 68 at GOLD 3 puts auto-PEEP in its band [ENG]", tag: 'P' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.25, 0.05], [0.5, 0.1], [0.75, 0.2], [1, 0.3]], src: "main §1.5 'copd' VD/VT 0.35/0.40/0.50/0.60 − 0.3 normal [ENG conversion]; §5 row 'Dead space'", tag: 'TXT', q: 'Q19' },
      { key: 'vqLow', op: 'add', v: [[0, 0], [0.25, 0.03], [0.5, 0.06], [0.75, 0.1], [1, 0.13]], src: "main §1.5 'copd' V/Q admixture 0.05/0.08/0.12/0.15 − healthy 0.02 [ENG conversion]; §5 row 'Shunt vs low V/Q'", tag: 'TXT' },
      { key: 'co2Slope', op: 'mul', v: [[0, 1], [0.25, 1], [0.5, 0.8], [0.75, 0.6], [1, 0.4]], src: "main §1.5 'copd' CO2 slope ×1/0.8/0.6/0.4", tag: 'ENG' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.5, 1], [0.75, 1.3], [1, 2]], src: "main §1.5 'copd' PVR ×1/1/1.3/2; §5 row 'PVR' (pvrReact 1.3, cor pulmonale GOLD 4)", tag: 'TXT' },
      { key: 'frc', op: 'mul', v: [[0, 1], [0.75, 1.2], [1, 1.4]], src: "§5 row 'FRC': ×1.2 GOLD 3, ×1.4 GOLD 4 (Stoelting 8e ch. 2 p. 27); GOLD 1–2 interpolated [ENG]", tag: 'TXT' },
      { key: 'tIt', op: 'set', v: [[0, 0.4], [0.25, 0.55], [1, 0.55]], src: "§5 row 'Airway → pleural transmission': 0.55 (Pepe & Marini 1982 direction / [ENG] number)", tag: 'ENG' },
      { key: 'dlFactor', op: 'mul', v: 0.6, src: "§5 row 'Diffusion': emphysema 0.5–0.7 → 0.6 at GOLD 4 (bronchitic 0.9) [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.75,
      crs: [43, 75],
      rInsp: [16, 33],
      autoPeep: [4, 8],
      alphaDeg: [120, 130],
      gapPaEt: [5, 15],
      shunt: [0, 0.05],
      peep5to15: 'down',
      src: "§5 rows 'Static compliance'/'Inspiratory R' (Arnal IQR), 'Auto-PEEP' GOLD 3 4–8 (VT 8 mL/kg), 'Capnogram alpha' 125°, 'Dead space' gap 5–15, 'External PEEP'",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'Induction hypotension after vigorous bag ventilation is auto-PEEP until proven otherwise: disconnect for 30 s.',
  },
  // ── §6 ARDS by Berlin grade ──────────────────────────────────────────────────────────────────
  {
    id: 'ards',
    label: 'ARDS (Berlin mild / moderate / severe; population-mean recruitability)',
    section: 6,
    sided: false,
    grades: [{ name: 'mild', severity: 0.33 }, { name: 'moderate', severity: 0.67 }, { name: 'severe', severity: 1 }],
    effects: [
      { key: 'crs', op: 'mul', v: [[0, 1], [0.33, 0.727], [0.67, 0.636], [1, 0.545]], src: "§6 row 'Static compliance': 40/35/30 mL/cmH2O ÷ 55 [ENG conversion] (Arnal 2018; Pulse 40/35/33, Maj 2023)", tag: 'P', q: 'Q73' },
      { key: 'raw', op: 'mul', v: [[0, 1], [0.33, 1.2], [1, 1.2]], src: "§6 row 'Inspiratory resistance': 12 (Arnal 12 [9–14]; Pulse 12) ÷ 10", tag: 'P' },
      { key: 'tIt', op: 'set', v: [[0, 0.4], [0.33, 0.2], [1, 0.2]], src: "§6 row 'Lung vs chest-wall elastance': pulmonary ARDS tIt 0.2 (extrapulmonary/abdominal 0.5) (Dellinger 5e ch. 11 p. 159)", tag: 'TXT' },
      { key: 'atel', op: 'add', v: [[0, 0], [0.33, 0.0875], [0.67, 0.1225], [1, 0.1575]], src: "§6 'Non-aerated lung' 0.25/0.35/0.45 × recruitFrac 0.35 (pop. mean; high 0.5 → 0.125/0.175/0.225, low 0.15) [ENG split]", tag: 'P', q: 'Q73' },
      { key: 'consol', op: 'add', v: [[0, 0], [0.33, 0.1625], [0.67, 0.2275], [1, 0.2925]], src: "§6 'Non-aerated lung' × (1 − 0.35) (high recruiter 0.5 → 0.125/0.175/0.225; low 0.15 → 0.2125/0.2975/0.3825) [ENG split]", tag: 'P', q: 'Q73' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.33, 0.24], [0.67, 0.27], [1, 0.35]], src: "§6 row 'Dead space': VD/VT 0.54/0.57/0.65 − 0.3 normal [ENG conversion] (Nuckton 2002; Pulse/Maj 2023)", tag: 'P' },
      { key: 'hpv', op: 'set', v: [[0, 0.5], [0.33, 0.3], [1, 0.3]], src: "§6 row 'HPV': hpvRegional 0.3 (partly lost in inflammation/sepsis)", tag: 'VERIFY' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.33, 1.5], [0.67, 2], [1, 2.5]], src: "§6 row 'PVR / acute cor pulmonale': ×1.5/2/2.5 (Mekontso Dessap 2016 prevalence / [ENG] multipliers)", tag: 'ENG', q: 'Q74' },
      { key: 'pOpen', op: 'set', v: 45, src: "§6 row 'Recruitment manoeuvre': P_open 40–45 cmH2O → 45 at severe [ENG] (Dellinger 5e ch. 11 p. 162)", tag: 'ENG', q: 'Q73' },
      { key: 'tauRecS', op: 'set', v: 20, src: "§6 row 'Recruitment manoeuvre': τ_rec 10–30 s in ARDS → midpoint 20 at severe [ENG]", tag: 'ENG', q: 'Q73' },
    ],
    bands: {
      refSeverity: 0.67,
      crs: [35, 35],
      rInsp: [9, 15],
      autoPeep: [0, 1],
      plateau: [19, 19],
      drivingPressure: [14, 14],
      alphaDeg: [105, 110],
      gapPaEt: [10, 20],
      shunt: [0.3, 0.3],
      peep5to15: 'up',
      src: "§6 Crs 35, R 12 [9–15], τ 0.45 s (little auto-PEEP), ΔP = 490/35 [ENG], shunt 0.30 (row 'Shunt'), alpha 105–110, gap 10–20; PEEP 'up' = high recruiter",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'P/F is not the lung: two patients with the same P/F can differ tenfold in recruitability, so PEEP 15 helps one and harms the other.',
  },
  // ── §7 Pulmonary fibrosis / ILD ──────────────────────────────────────────────────────────────
  {
    id: 'ild',
    label: 'Pulmonary fibrosis / interstitial lung disease',
    section: 7,
    sided: false,
    grades: [{ name: 'mild (FVC 70–80 %)', severity: 0.3 }, { name: 'moderate (FVC 50–70 %)', severity: 0.6 }, { name: 'end-stage (FVC < 50 %)', severity: 0.9 }],
    effects: [
      { key: 'crs', op: 'mul', v: [[0, 1], [0.3, 0.818], [0.6, 0.582], [0.9, 0.364], [1, 0.364]], src: "§7 row 'Static respiratory compliance': 45/32/20 ÷ 55 [ENG conversion; held flat 0.9→1] (Nava & Rubini 1999)", tag: 'P' },
      { key: 'raw', op: 'mul', v: [[0, 1], [0.3, 1.1], [0.6, 1.3], [0.9, 1.7], [1, 1.7]], src: "§7 row 'Resistance': 11/13/17 ÷ 10 (Nava & Rubini 1999, Rrs 16.7 end-stage)", tag: 'P' },
      { key: 'tIt', op: 'set', v: [[0, 0.4], [0.9, 0.15], [1, 0.15]], src: "§7 row 'Lung vs chest wall': EL/Etot ≈ 0.9 → tIt 0.1–0.2 → 0.15 at end-stage [ENG knots] (Nava & Rubini; Dellinger ch. 11)", tag: 'P' },
      { key: 'frc', op: 'mul', v: [[0, 1], [0.3, 0.85], [0.6, 0.7], [0.9, 0.55], [1, 0.55]], src: "§7 row 'FRC / TLC': 0.85/0.7/0.55 [TXT]/[ENG]", tag: 'ENG' },
      { key: 'dlFactor', op: 'mul', v: [[0, 1], [0.3, 0.7], [0.6, 0.45], [0.9, 0.25], [1, 0.25]], src: "§7 row 'Diffusion factor': 0.7/0.45/0.25 (Stoelting 8e ch. 3 p. 47; Pulse diffusion area ×0.5/0.2/0.1)", tag: 'TXT' },
      { key: 'extraShunt', op: 'add', v: [[0, 0], [0.3, 0.02], [0.6, 0.05], [0.9, 0.1], [1, 0.1]], src: "§7 row 'Shunt / V/Q': shunt 0.02/0.05/0.10 [TXT]/[ENG]", tag: 'ENG' },
      { key: 'vqLow', op: 'add', v: [[0, 0], [0.3, 0.03], [0.9, 0.08], [1, 0.08]], src: "§7 row 'Shunt / V/Q': low V/Q 0.05–0.10 total − healthy 0.02, spread mild→end-stage [ENG conversion]", tag: 'ENG' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.3, 0.05], [0.6, 0.1], [0.9, 0.15], [1, 0.15]], src: "§7 row 'Dead space': +0.05/+0.10/+0.15 VD/VT", tag: 'ENG' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.3, 1], [0.6, 1.3], [0.9, 2], [1, 2]], src: "§7 row 'PVR': ×1.0/1.3/2.0 (vessel loss, fixed; Stoelting 8e ch. 3 p. 47)", tag: 'TXT' },
    ],
    bands: {
      refSeverity: 0.6,
      crs: [32, 32],
      rInsp: [13, 13],
      autoPeep: [0, 0.5],
      drivingPressure: [13, 15.5],
      alphaDeg: [100, 105],
      gapPaEt: [5, 10],
      peep5to15: 'none',
      src: "§7 rows Crs 32, R 13, 'Time constant' (PEEPi negligible), 'Ventilator at 6 mL/kg' ΔP 13 (490/32 ≈ 15.3 at ref VT [ENG]), 'Monitor signature', 'PEEP response'",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'Driving pressure is already high at "protective" volumes: accept a smaller VT and a higher RR, since there is no auto-PEEP penalty.',
  },
  // ── §8 Systemic sclerosis (composite) ────────────────────────────────────────────────────────
  {
    id: 'ssc',
    label: 'Systemic sclerosis (SSc-ILD + chest-wall skin; PH off by default)',
    section: 8,
    sided: false,
    effects: [
      { key: 'crs', op: 'mul', v: 0.739, src: "§8 row 'ILD component': §7 at sev 0.4 → Crs ×0.739 (interp. 0.818→0.582) [ENG]; Launay 2007; Stoelting 8e ch. 24 p. 502", tag: 'ENG' },
      { key: 'raw', op: 'mul', v: 1.167, src: "§8 'ILD component' §7 sev 0.4 → R ×1.167 (interp. 1.1→1.3) [ENG]", tag: 'ENG' },
      { key: 'frc', op: 'mul', v: 0.8, src: "§8 'ILD component' §7 sev 0.4 → FRC ×0.80 (interp. 0.85→0.7) [ENG]", tag: 'ENG' },
      { key: 'extraShunt', op: 'add', v: 0.03, src: "§8 'ILD component' §7 sev 0.4 → shunt 0.03 (interp. 0.02→0.05) [ENG]", tag: 'ENG' },
      { key: 'vqLow', op: 'add', v: 0.038, src: "§8 'ILD component' §7 sev 0.4 → low V/Q +0.038 (interp.) [ENG]", tag: 'ENG' },
      { key: 'vdAlv', op: 'add', v: 0.067, src: "§8 'ILD component' §7 sev 0.4 → +0.067 VD/VT (interp. 0.05→0.10) [ENG]", tag: 'ENG' },
      { key: 'pvr', op: 'mul', v: 1.1, src: "§8 'ILD component' §7 sev 0.4 → PVR ×1.1; PH component off by default (row 'PH component', Q76)", tag: 'ENG', q: 'Q76' },
      { key: 'ccw', op: 'mul', v: 0.6, src: "§8 row 'Chest-wall compliance (skin sclerosis)': 200 → 120 mL/cmH2O in diffuse cutaneous disease [TXT]/[ENG]", tag: 'ENG', q: 'Q76' },
      { key: 'tIt', op: 'set', v: 0.5, src: "§8 row 'Chest-wall compliance': tIt ↑ 0.4 → 0.5 (chosen over §7 ILD's lower tIt) [ENG]", tag: 'ENG', q: 'Q76' },
      { key: 'dlFactor', op: 'mul', v: 0.5, src: "§8 row 'Diffusion': 0.5 (vasculopathy + ILD; Launay 2007)", tag: 'P' },
    ],
    bands: {
      refSeverity: 1,
      src: "§8 gives no numeric ventilator/monitor band; ventilator 'as §7 + §1' (small VT, no permissive hypercapnia if PH, modest PEEP)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'Finger-probe "desaturation" in a cold theatre may be Raynaud: check the waveform and perfusion index and move the probe before escalating FiO2 or PEEP.',
  },
  // ── §9 Kyphoscoliosis and chest-wall restriction ─────────────────────────────────────────────
  {
    id: 'chestWall',
    label: 'Kyphoscoliosis / chest-wall restriction',
    section: 9,
    sided: false,
    grades: [{ name: 'Cobb 60–70°', severity: 0.33 }, { name: 'Cobb 70–100°', severity: 0.67 }, { name: 'Cobb > 100°', severity: 1 }],
    effects: [
      { key: 'ccw', op: 'mul', v: [[0, 1], [0.33, 0.6], [0.67, 0.35], [1, 0.2]], src: "§9 row 'Chest-wall compliance': 120/70/40 ÷ 200 [ENG conversion] (Stoelting 8e ch. 3 p. 48; Bergofsky not opened)", tag: 'VERIFY', q: 'Q77' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.33, 1], [0.67, 0.887], [1, 0.763]], src: "§9 row 'Resulting Crs' ≈45/32/20: the row's LUNG part ×1/0.85/0.7 expressed on the healthy-chest-wall scale conditions.ts converts from (1/(1/(75.9·m) + 1/200) ÷ 55); the chest wall comes from `ccw`. Stage 7b executor fix: the extraction put the whole-system 45/32/20 here AND the stiff chest wall in `ccw`, counting the wall twice (measured Crs 24.6 vs 32) [ENG]", tag: 'ENG', q: 'Q77' },
      { key: 'tIt', op: 'set', v: [[0, 0.4], [0.33, 0.5], [0.67, 0.6], [1, 0.7]], src: "§9 row 'Airway → pleural transmission': 0.5/0.6/0.7 (main §2.2: 0.7 for a stiff chest wall)", tag: 'TXT' },
      { key: 'frc', op: 'mul', v: [[0, 1], [0.33, 0.85], [0.67, 0.7], [1, 0.5]], src: "§9 row 'FRC, VC': 0.85/0.7/0.5 (Stoelting 8e ch. 3 p. 48)", tag: 'TXT' },
      { key: 'extraShunt', op: 'add', v: [[0, 0], [0.33, 0.02], [0.67, 0.05], [1, 0.1]], src: "§9 row 'Shunt / A–a gradient': +0.02/+0.05/+0.10 (compressed concave-side lung; Stoelting 8e ch. 3 p. 48)", tag: 'TXT' },
      { key: 'co2Slope', op: 'mul', v: [[0, 1], [0.33, 1], [0.67, 0.8], [1, 0.5]], src: "§9 row 'Chronic hypoventilation': CO2 slope ×1/0.8/0.5 (Stoelting 8e ch. 3 p. 48)", tag: 'TXT' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.33, 1], [0.67, 1.2], [1, 2]], src: "§9 row 'PVR': ×1/1.2/2 (hypoxic, cor pulmonale)", tag: 'TXT' },
    ],
    bands: {
      refSeverity: 0.67,
      crs: [32, 32],
      rInsp: [10, 10],
      autoPeep: [0, 0.5],
      alphaDeg: [100, 110],
      src: "§9 rows 'Resulting Crs' 32, 'Resistance, τ' (normal R, τ 0.3 s, no auto-PEEP), 'Monitor signature' (normal capnogram shape)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'A high Pplat with a stiff chest wall is not a high Pplat with stiff lungs: estimate transpulmonary pressure before cutting VT into hypercapnia.',
  },
  // ── §10 Obesity (BMI class via main §1.3; OHS flag not encoded) ─────────────────────────────
  {
    id: 'obesity',
    label: 'Obesity (anaesthetised, supine; BMI class)',
    section: 10,
    sided: false,
    grades: [{ name: 'BMI 25–30', severity: 0.25 }, { name: 'BMI 30–35 (I)', severity: 0.5 }, { name: 'BMI 35–40 (II)', severity: 0.75 }, { name: 'BMI ≥ 40 (III)', severity: 1 }],
    effects: [
      { key: 'crs', op: 'mul', v: [[0, 1], [0.25, 0.95], [0.5, 0.85], [0.75, 0.75], [1, 0.65]], src: "main §1.3 Crs ×0.95/0.85/0.75/0.65; §10 row 'Crs' 32 vs 53 at BMI 40 agrees (Behazin 2010)", tag: 'P' },
      { key: 'ccw', op: 'mul', v: 0.874, src: "§10 row 'Chest-wall compliance': 195 vs controls 223 → ×0.874, barely changed (Behazin 2010; Pelosi 1998)", tag: 'P', q: 'Q78' },
      { key: 'tIt', op: 'set', v: 0.425, src: "§10 row 'Airway → pleural transmission': 0.35–0.5 → 0.425 (Behazin) chosen over main §2.2's 0.7 for obesity [ENG]", tag: 'P', q: 'Q78' },
      { key: 'raw', op: 'mul', v: 1.3, src: "§10 row 'Resistance': ×1.3 at BMI 40 (Pelosi 1998)", tag: 'P' },
      { key: 'frc', op: 'mul', v: [[0, 1], [0.25, 0.9], [0.5, 0.75], [0.75, 0.65], [1, 0.5]], src: "main §1.3 FRC factor 0.9/0.75/0.65/0.5; §10 row 'FRC / EELV' (Reinius 2009: EELV halves)", tag: 'P', q: 'Q8' },
      { key: 'atel', op: 'add', v: [[0, 0], [0.25, 0.011], [0.5, 0.027], [0.75, 0.043], [1, 0.045]], src: "§10 'Atelectasis' 0.11 − healthy GA 0.06 (main §4.1) = 0.05 excess; lower BMI via main §1.3 ×1.2/1.5/1.8; ×recruitFrac 0.9 [ENG]", tag: 'P' },
      { key: 'consol', op: 'add', v: [[0, 0], [0.25, 0.001], [0.5, 0.003], [0.75, 0.005], [1, 0.005]], src: "§10 'Atelectasis' excess × (1 − recruitFrac 0.9) (row 'Recruitability', Reinius 2009) [ENG split]", tag: 'P' },
      { key: 'pOpen', op: 'set', v: 50, src: "§10 row 'Opening pressure': 45–55 → 50 cmH2O (Reinius 2009 used 55)", tag: 'P' },
    ],
    bands: {
      refSeverity: 1,
      crs: [24, 40],
      alphaDeg: [100, 110],
      gapPaEt: [5, 8],
      shunt: [0.1, 0.15],
      peep5to15: 'none',
      src: "§10 rows 'Crs' 32 (24–40), 'Atelectasis' shunt +0.10–0.15, 'PEEP alone (no RM)' no oxygenation gain, 'Monitor signature' (normal shape, gap 5–8)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'PEEP without a recruitment manoeuvre does little in the morbidly obese: open the lung first, then keep it open.',
  },
  // ── §11 Pneumonia (lobar, unilateral) ────────────────────────────────────────────────────────
  // Severity = extent / 0.5 of total lung (range 0.1–0.5); default one lower lobe 0.2 → severity 0.4.
  // Regional fractions are per AFFECTED lung: whole-lung fraction ÷ 0.5 (one lung = 0.5, §15) [ENG].
  {
    id: 'pneumonia',
    label: 'Pneumonia (lobar, unilateral)',
    section: 11,
    sided: true,
    effects: [
      { key: 'consol', op: 'add', v: [[0, 0], [0.4, 0.36], [1, 0.9]], where: 'affected', src: "§11 'Consolidated fraction' 0.2 of lung → 0.4 of one lung × (1 − recruitFrac 0.1) [ENG split]; extent 0.5 at sev 1 [ENG]", tag: 'ENG', q: 'Q79' },
      { key: 'atel', op: 'add', v: [[0, 0], [0.4, 0.04], [1, 0.1]], where: 'affected', src: "§11 'Consolidated fraction' (0.4 of one lung) × recruitFrac 0.1 (row 'Recruitability', Dellinger 5e ch. 40 p. 660) [ENG split]", tag: 'ENG', q: 'Q79' },
      { key: 'hpv', op: 'set', v: [[0, 0.5], [0.2, 0.25], [1, 0.25]], where: 'affected', src: "§11 row 'HPV in the infected lobe': 0.25, half of normal (endotoxin/NO) (Dellinger 5e ch. 40 p. 660)", tag: 'TXT' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.4, 0.84], [1, 0.6]], src: "§11 row 'Compliance': ×(1 − 0.8·consol) with whole-lung consol 0.2 → 0.84 (0.5 → 0.6) (Dellinger 5e ch. 40 p. 660)", tag: 'TXT' },
      { key: 'raw', op: 'mul', v: [[0, 1], [0.4, 1.3], [1, 1.3]], src: "§11 row 'Resistance, secretions': ×1.3 (range 1–2); secretion noise events not encoded", tag: 'ENG' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.4, 0.05], [1, 0.125]], src: "§11 row 'Dead space': +0.05 at default extent; linear with extent [ENG]", tag: 'ENG' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.4, 1.1], [1, 1.25]], src: "§11 row 'PVR': ×1.1 at default extent; linear with extent [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.4,
      alphaDeg: [105, 110],
      shunt: [0.15, 0.25],
      spo2Fio2_04: [88, 93],
      peep5to15: 'down',
      src: "§11 rows 'Shunt' ≈0.15–0.25 (Cooligan 1982), 'Monitor signature' (SpO2 88–93 % on FiO2 0.4, alpha 105–110°), 'PEEP / VT response' paradoxical",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'More PEEP can make unilateral pneumonia worse (over-distends the good lung and diverts flow to the shunt): watch SpO2 after each step.',
  },
  // ── §12 Atelectasis (lobar collapse preset; postopAtel not encoded) ──────────────────────────
  // Severity = collapsed whole-lung fraction / 0.5; default RLL 0.2 → severity 0.4; per affected lung 0.4.
  {
    id: 'atelectasis',
    label: 'Atelectasis: lobar collapse (mucus plug)',
    section: 12,
    sided: true,
    defaultSide: 'R',
    effects: [
      { key: 'consol', op: 'add', v: [[0, 0], [0.4, 0.4], [1, 1]], where: 'affected', src: "§12 'Lobar collapse: volume' RLL 0.2 of lung → 0.4 of right lung; plug recruitFrac 0 → all non-recruitable [ENG split]; whole lung 0.5", tag: 'TXT' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.4, 0.7], [1, 0.25]], src: "§12 row 'Compliance': ×(1 − 1.5·atel) main §4.1 rule, whole-lung atel 0.2 → 0.7 (0.5 → 0.25)", tag: 'TXT' },
    ],
    bands: {
      refSeverity: 0.4,
      alphaDeg: [105, 105],
      shunt: [0.1, 0.12],
      peep5to15: 'none',
      src: "§12 rows 'Lobar collapse: shunt' lower lobe 0.10–0.12 after HPV, 'Monitor signature' alpha 105°, 'Recruitability' plug 0 (RM does nothing)",
    },
    needs: ['7b', 'V'],
    pitfall: 'A recruitment manoeuvre cannot open a lobe behind a mucus plug; suction or bronchoscopy does, and a failed RM suggests a plug or a misplaced tube.',
  },
  // ── §13 Pulmonary oedema (cardiogenic default; non-cardiogenic values in src) ─────────────────
  {
    id: 'pulmOedema',
    label: 'Pulmonary oedema (cardiogenic default)',
    section: 13,
    sided: false,
    effects: [
      { key: 'extraShunt', op: 'add', v: 0.175, src: "§13 row 'Shunt': cardiogenic 0.10–0.25 → 0.175 (non-cardiogenic 0.15–0.35); lung-water shunt, PEEP ×(1 − 0.04·PEEP) main §4.5 [ENG]", tag: 'ENG', q: 'Q25' },
      { key: 'crs', op: 'mul', v: 0.75, src: "§13 row 'Compliance': cardiogenic ×0.7–0.8 → 0.75 (non-cardiogenic ×0.6–0.7) (main §4.5) [ENG]", tag: 'ENG' },
      { key: 'raw', op: 'mul', v: 1.35, src: "§13 row 'Resistance (\"cardiac asthma\")': cardiogenic ×1.2–1.5 → 1.35 (non-cardiogenic ×1.1) (main §4.5) [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 1,
      alphaDeg: [115, 120],
      shunt: [0.1, 0.25],
      peep5to15: 'up',
      src: "§13 rows 'Resistance' (alpha 115–120° cardiogenic), 'Shunt' 0.10–0.25, 'PEEP / CPAP response' strong (shunt ×(1 − 0.04·PEEP))",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'Desaturation after laryngospasm is often negative-pressure pulmonary oedema, not aspiration, and can appear up to 2–3 h later in PACU.',
  },
  // ── §14 Pleural effusion ─────────────────────────────────────────────────────────────────────
  // Severity = volume / 3000 mL (range 200–3000); default 1.5 L → severity 0.5.
  {
    id: 'effusion',
    label: 'Pleural effusion',
    section: 14,
    sided: true,
    effects: [
      { key: 'atel', op: 'add', v: [[0, 0], [0.5, 0.072], [1, 0.144]], where: 'affected', src: "§14 'Compression atelectasis' +0.08/L whole lung → 0.24 of one lung at 1.5 L × recruitFrac 0.3 [ENG split]", tag: 'ENG', q: 'Q81' },
      { key: 'consol', op: 'add', v: [[0, 0], [0.5, 0.168], [1, 0.336]], where: 'affected', src: "§14 'Compression atelectasis' (0.24 of one lung at 1.5 L) × (1 − recruitFrac 0.3, fluid present; 0.8 after drainage) [ENG split]", tag: 'ENG', q: 'Q81' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.5, 0.82], [1, 0.64]], src: "§14 row 'Compliance': ×(1 − 0.12 per L) (Razazi 2014 direction / [ENG] size)", tag: 'ENG' },
      { key: 'frc', op: 'mul', v: [[0, 1], [0.5, 0.643], [1, 0.286]], src: "§14 row 'EELV / FRC': −0.5 × effusion volume ÷ FRC 2100 mL (Stage 3 30 mL/kg × 70) [ENG conversion] (Razazi 2014)", tag: 'ENG', q: 'Q81' },
      { key: 'pPtx', op: 'set', v: [[0, 0], [0.5, 1.1], [1, 2.2]], where: 'affected', src: "§14 row 'Pleural pressure': +1 cmH2O per L → 0.74 mmHg/L [ENG conversion]; small haemodynamic effect (Razazi 2014)", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.5,
      alphaDeg: [100, 110],
      peep5to15: 'none',
      src: "§14 rows 'Monitor signature' (normal capnogram, SpO2 −2–5 %, Pplat +2–4, no BP change), 'Recruitability' 0.3 while fluid present",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'An effusion is not a tension pneumothorax: haemodynamics are usually preserved, so look for another cause before rushing a drain in an unstable patient.',
  },
  // ── §15 Pneumothorax: simple ─────────────────────────────────────────────────────────────────
  // Severity = size (fraction of hemithorax); default 0.3; 1.0 = complete collapse, extrapolated [ENG].
  {
    id: 'ptxSimple',
    label: 'Pneumothorax: simple',
    section: 15,
    sided: true,
    effects: [
      { key: 'consol', op: 'add', v: [[0, 0], [0.3, 0.3], [1, 1]], where: 'affected', src: "§15 'Collapsed lung fraction' size × 0.5 of lung = size of one lung; recruitFrac 0 until drained → non-recruitable [ENG]", tag: 'ENG' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.3, 0.82], [1, 0.4]], src: "§15 row 'Compliance': ×(1 − size·0.6) [ENG]; size 1 extrapolated [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.3,
      shunt: [0.07, 0.07],
      peep5to15: 'none',
      src: "§15 rows 'Shunt' ≈0.07 (main §4.2), 'Recruitability' 0 until drained, 'Monitor signature' (Ppeak +3–8 VC, EtCO2 ≈ unchanged, ABP normal)",
    },
    needs: ['7b', 'V'],
    pitfall: 'Stop N2O in any patient with a pneumothorax or suspected occult chest trauma: it expands the air space towards tension.',
  },
  // ── §16 Pneumothorax: tension (ventilated column) ────────────────────────────────────────────
  {
    id: 'ptxTension',
    label: 'Pneumothorax: tension (ventilated)',
    section: 16,
    sided: true,
    effects: [
      { key: 'pPtx', op: 'set', v: 25, where: 'affected', src: "§16 row 'Pleural pressure build-up': ventilated pPtx 15–25 mmHg within 2–5 min; 25 at sev 1 (PEA ≈ 20–25) [ENG]; main §2.2", tag: 'ENG', q: 'Q82' },
      { key: 'consol', op: 'add', v: 1, where: 'affected', src: "§16 row 'Hypoxia': collapsed ipsilateral lung (non-recruitable until decompressed) [ENG]; compressed contralateral lung not encoded", tag: 'ENG' },
      { key: 'crs', op: 'mul', v: 0.5, src: "§33 row 16: Crs ×0.5 (chosen over §16 'Airway pressure' Ppeak +10–20 at VT 490 ≈ ×0.31–0.47 and §15 formula at size 1 = 0.4) [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.8,
      shunt: [0.3, 0.5],
      peep5to15: 'down',
      src: "§16 rows 'Hypoxia' shunt 0.3–0.5, 'Venous return / CO' (CO −50–80 %), H6: CVP +5–15, Ppeak +10–20, EtCO2 ↓ with CO",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'Under PPV a tension pneumothorax is a minutes-long emergency, not a radiological diagnosis: rising Ppeak, falling BP and EtCO2, rising CVP mean decompress now.',
  },
  // ── §17 Haemothorax ──────────────────────────────────────────────────────────────────────────
  // Severity = volume / 3000 mL (range 0.3–3 L); default 1.5 L → severity 0.5. Blood-volume loss is main §5b.4 (not a lung key).
  {
    id: 'haemothorax',
    label: 'Haemothorax',
    section: 17,
    sided: true,
    effects: [
      { key: 'atel', op: 'add', v: [[0, 0], [0.5, 0.048], [1, 0.096]], where: 'affected', src: "§17 'Lung compression' as §14: atel +0.08/L → 0.24 of one lung at 1.5 L × recruitFrac 0.2 (row 'Recruitability') [ENG split]", tag: 'ENG' },
      { key: 'consol', op: 'add', v: [[0, 0], [0.5, 0.192], [1, 0.384]], where: 'affected', src: "§17 'Lung compression' (0.24 of one lung at 1.5 L) × (1 − recruitFrac 0.2; clotted 0.3) [ENG split]", tag: 'ENG' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.5, 0.82], [1, 0.64]], src: "§17 row 'Lung compression': Crs ×(1 − 0.12/L) as §14 [ENG]", tag: 'ENG' },
      { key: 'frc', op: 'mul', v: [[0, 1], [0.5, 0.643], [1, 0.286]], src: "§17 row 'Lung compression': EELV −0.5 × volume ÷ FRC 2100 mL (Stage 3 30 mL/kg × 70) [ENG conversion]", tag: 'ENG' },
      { key: 'pPtx', op: 'set', v: [[0, 0], [0.5, 3], [1, 6]], where: 'affected', src: "§17 row 'Pleural pressure': +1–3 mmHg per L → 2/L [ENG]; massive > 2.5 L tension-like shift not encoded", tag: 'ENG', q: 'Q83' },
    ],
    bands: {
      refSeverity: 0.5,
      src: "§17 row 'Monitor signature' is relative only (tachycardia, PPV > 15 %, CVP falls, SpO2 −2–5 %, Ppeak modest ↑, EtCO2 ↓ with CO); no numeric lung band",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'CVP falls in haemothorax and rises in tension pneumothorax, although both give hypotension and a high Ppeak.',
  },
  // ── §18 Pulmonary thromboembolism ────────────────────────────────────────────────────────────
  // peFrac φ 0.2/0.35/0.6 mapped through main §2.2: PVR × 1/(1 − φ) × (1 + peVaso 0.5·φ); VD_alv = φ·VA ≈ 0.7·φ·VT [ENG].
  {
    id: 'pe',
    label: 'Pulmonary thromboembolism',
    section: 18,
    sided: false,
    grades: [{ name: 'low risk', severity: 0.33 }, { name: 'intermediate (RV dysfunction)', severity: 0.67 }, { name: 'high risk (massive)', severity: 1 }],
    effects: [
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.33, 1.375], [0.67, 1.808], [1, 3.25]], src: "§18 row 'Obstruction fraction' φ 0.2/0.35/0.6 via main §2.2 PVR×1/(1−φ)×(1+0.5φ) [ENG]; §33: ×3–5 high risk", tag: 'P', q: 'Q27' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.33, 0.14], [0.67, 0.245], [1, 0.42]], src: "§18 row 'Alveolar dead space': φ × VA, VA ≈ 0.7 VT → 0.7φ [ENG conversion]; gap 5/10/15–25 (main §4.4)", tag: 'TXT' },
      { key: 'extraShunt', op: 'add', v: [[0, 0], [0.67, 0], [1, 0.1]], src: "§18 row 'Hypoxaemia mechanism': shunt +0.05–0.15 at φ ≥ 0.5 → 0.10 high risk (Dellinger 5e ch. 42 p. 673) [ENG]", tag: 'TXT' },
      { key: 'raw', op: 'mul', v: [[0, 1], [0.67, 1], [1, 1.2]], src: "§18 row 'Mechanics': ≈ normal; serotonin bronchoconstriction R ×1.2 in massive", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 1,
      alphaDeg: [105, 105],
      gapPaEt: [15, 25],
      peep5to15: 'down',
      src: "§18 rows 'Alveolar dead space' (gap 15–25 high risk), 'Monitor signature' (normal shape, alpha ≈105°), 'Ventilator' (avoid high PEEP, RV afterload); H5",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'A sudden EtCO2 fall with an unchanged capnogram shape means a perfusion problem (PE, low CO, embolism), not a ventilation one.',
  },
  // ── §19 Fat embolism (BCIS grades; late FES not encoded) ─────────────────────────────────────
  {
    id: 'fatEmbolism',
    label: 'Fat embolism / bone cement implantation syndrome',
    section: 19,
    sided: false,
    grades: [{ name: 'BCIS 1', severity: 0.33 }, { name: 'BCIS 2', severity: 0.67 }, { name: 'BCIS 3', severity: 1 }],
    effects: [
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.33, 1.222], [0.67, 1.667], [1, 2.333]], src: "§19 'Microembolic obstruction' φ 0.1/0.25/0.4, peVaso 1.0 via main §2.2 PVR×1/(1−φ)×(1+φ) [ENG]; §33 ×1.5–3", tag: 'ENG', q: 'Q84' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.33, 0.07], [0.67, 0.175], [1, 0.28]], src: "§19 'Microembolic obstruction' φ 0.1/0.25/0.4 as §18 dead space 0.7φ [ENG conversion]", tag: 'ENG', q: 'Q84' },
    ],
    bands: {
      refSeverity: 0.33,
      src: "§19 'Monitor signature' at cementing is relative only (EtCO2 −5–15, SpO2 −3–10 %, MAP −20–40 %, CVP/PAP ↑); BCIS grade bands are SpO2/SBP targets (Olsen 2014)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'Hypotension with an EtCO2 drop at cementing is BCIS until proven otherwise: tell the surgeon, give FiO2 1.0 and support the RV.',
  },
  // ── §20 Venous air embolism ──────────────────────────────────────────────────────────────────
  // §20 gives no default entry rate; severity 1 := steady entry 4 mL/kg/min → peFrac 0.2 (row 'Air → obstruction' 0.05 per mL/kg/min) [ENG].
  {
    id: 'vae',
    label: 'Venous air embolism (continuous entry)',
    section: 20,
    sided: false,
    effects: [
      { key: 'pvr', op: 'mul', v: 1.375, src: "§20 rows 'Air → obstruction' (φ 0.2 at sev 1 [ENG]) + 'Vasoconstrictor factor' 0.5 via main §2.2 PVR×1/(1−φ)×(1+0.5φ)", tag: 'ENG', q: 'Q85' },
      { key: 'vdAlv', op: 'add', v: 0.14, src: "§20 'Air → obstruction' φ 0.2 → dead space 0.7φ as §18 [ENG]; gap ≈ 8 fits row 'EtCO2' fall 2–10 mmHg", tag: 'ENG', q: 'Q85' },
    ],
    bands: {
      refSeverity: 1,
      alphaDeg: [100, 110],
      src: "§20 row 'EtCO2': falls 2–10 mmHg within 1–3 breaths with normal capnogram shape; SpO2 late; RV air lock (bolus) not encoded",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'An EtCO2 drop of a few mmHg in a sitting craniotomy is air until proven otherwise; the blood pressure falls later.',
  },
  // ── §21 Aspiration (acid 0.4 mL/kg non-particulate = severity 1; phases collapsed into one preset) ─
  {
    id: 'aspiration',
    label: 'Aspiration (acid, non-particulate; right lower lobe)',
    section: 21,
    sided: true,
    defaultSide: 'R',
    effects: [
      { key: 'raw', op: 'mul', v: 2.51, src: "§21 'Immediate bronchospasm' §2 sev 0.3–0.6 → 0.45: ×(1+5·0.45^1.5) = 2.51 [ENG]; §33 R ×1.5–2.5 early", tag: 'ENG', q: 'Q86' },
      { key: 'rawExp', op: 'set', v: 1.525, src: "§21 'Immediate bronchospasm' §2 sev 0.45: 1.3 + 0.5·0.45 [ENG]", tag: 'ENG' },
      { key: 'crs', op: 'mul', v: 0.75, src: "§21 row 'Chemical pneumonitis': Crs ×0.7–0.8 → 0.75 [TXT]/[ENG]", tag: 'ENG' },
      { key: 'extraShunt', op: 'add', v: 0.2, src: "§21 row 'Chemical pneumonitis': shunt 0.1–0.3 → 0.2 (lung-water shunt; recruitFrac 0.4 not encodable without atel) [ENG]", tag: 'ENG' },
      { key: 'hpv', op: 'set', v: 0.3, where: 'affected', src: "§21 row 'HPV in injured lung': 0.3 (inflammation)", tag: 'VERIFY' },
    ],
    bands: {
      refSeverity: 1,
      alphaDeg: [120, 130],
      shunt: [0.1, 0.3],
      peep5to15: 'up',
      src: "§21 rows 'Immediate bronchospasm' (alpha 120–130°), 'Chemical pneumonitis' shunt 0.1–0.3, 'Recruitability' 0.4 (PEEP helps partly)",
    },
    needs: ['7b', 'V'],
    pitfall: 'Most aspirations are silent and benign: observe for 2 h, and no signs by then means no sequelae (Warner).',
  },
  // ── §22 One-lung ventilation (affected = non-ventilated lung) ────────────────────────────────
  {
    id: 'olv',
    label: 'One-lung ventilation (lateral, DLT)',
    section: 22,
    sided: true,
    defaultSide: 'L',
    mainstem: 'blockAffected',
    effects: [
      { key: 'raw', op: 'mul', v: 1.5, src: "§33 row 22: R insp ×1.5 (DLT)", tag: 'ENG' },
      { key: 'perfShare', op: 'mul', v: 0.89, where: 'affected', src: "§22 row 'Non-ventilated lung perfusion share': gravity 40 % in lateral ÷ normal 45 % [ENG conversion]; HPV then → 20–25 % (Miller 10e ch. 49 p. 1538)", tag: 'TXT', q: 'Q35' },
      { key: 'pvr', op: 'mul', v: 1.35, src: "§22 row 'PVR / RV': OLV raises PVR ×1.2–1.5 → 1.35 (Stoelting 8e ch. 9 p. 200) [TXT]/[ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 1,
      crs: [25, 30],
      shunt: [0.2, 0.3],
      peep5to15: 'up',
      src: "§22 rows 'Ventilated lung mechanics' (≈0.5 × two-lung Crs), 'Non-ventilated lung perfusion share' (shunt 20–30 %), 'PEEP vs auto-PEEP' (+5 PEEP helps if PEEPi < 2)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'Desaturation on OLV: check tube position first (fibreoptic), then FiO2, recruitment/PEEP, CPAP to the operative lung, then two-lung ventilation.',
  },
  // ── §23 Endobronchial intubation (right mainstem default → left lung blocked) ────────────────
  {
    id: 'endobronchial',
    label: 'Endobronchial intubation (right mainstem)',
    section: 23,
    sided: true,
    defaultSide: 'L',
    mainstem: 'blockAffected',
    effects: [
      // §23 'Collapse of the non-ventilated lung' is NOT an effect: the mainstem block makes it emerge in recruit.ts
      // (absorption τ 5 min at FiO2 1.0, 20–40 min at 0.3–0.5; recruitable only by a manoeuvre after withdrawal).
    ],
    bands: {
      refSeverity: 1,
      crs: [27.5, 30.25],
      alphaDeg: [100, 110],
      shunt: [0.15, 0.25],
      src: "§23 rows 'Compliance' ×0.5–0.55 of 55, 'Shunt' +0.25 → +0.15 with HPV (SpO2 85–92 % on FiO2 0.5), 'Monitor signature' (normal capnogram shape)",
    },
    needs: ['7b', 'V'],
    pitfall: 'A rising Ppeak after pneumoperitoneum or head-down tilt can be the tube migrating into a bronchus, not the abdomen.',
  },
  // ── §24 Bronchopleural fistula ───────────────────────────────────────────────────────────────
  // Severity: moderate default leak 0.2 of VT := 0.5; 1.0 = range top 0.8 [ENG]. Mechanics otherwise "as underlying".
  {
    id: 'bpf',
    label: 'Bronchopleural fistula (drain present)',
    section: 24,
    sided: true,
    effects: [
      { key: 'leakFrac', op: 'add', v: [[0, 0], [0.5, 0.2], [1, 0.8]], where: 'affected', src: "§24 row 'Leak conductance': 0.2 of VT at Pplat 25 (moderate), range 0.05–0.8; pressure-driven, PEEP drives exp leak [ENG]", tag: 'ENG', q: 'Q87' },
    ],
    bands: {
      refSeverity: 0.5,
      alphaDeg: [100, 110],
      src: "§24 row 'Capnogram': EtCO2 plateau normal but PaCO2 ↑ (gap widens); 'Monitor signature': inspired–expired VT difference is the key sign",
    },
    needs: ['7b', 'V'],
    pitfall: 'Look at the difference between inspired and expired VT: that is the leak, and PEEP makes it bigger.',
  },
  // ── §25 Tracheal and tube obstruction (ETT lumen, partial default) ──────────────────────────
  {
    id: 'airwayObstruction',
    label: 'Tracheal / tube obstruction (ETT lumen, fixed lesion)',
    section: 25,
    sided: false,
    effects: [
      { key: 'raw', op: 'mul', v: [[0, 1], [0.5, 5], [1, 20]], src: "§25 intro/main §4.3 'Tube kink / secretions': kink ×5–20 (flow-dependent; rawK2 20–100 not encodable) [ENG knots]", tag: 'ENG', q: 'Q87' },
      { key: 'rawExp', op: 'set', v: 1, src: "§25 row 'Inspiratory vs expiratory': fixed ETT lesion 1.0 symmetric (intrathoracic variable 2–4, extrathoracic 0.5)", tag: 'TXT' },
    ],
    bands: {
      refSeverity: 0.5,
      alphaDeg: [115, 130],
      src: "§25 row 'Capnogram': partial obstruction alpha 115–130°, lower EtCO2; 'Differential vs bronchospasm': Ppeak ↑ with normal Pplat",
    },
    needs: ['7b', 'V'],
    pitfall: 'High Ppeak with a normal Pplat is resistance, and the tube is the commonest resistance: pass a suction catheter before giving bronchodilators.',
  },
  // ── §26 Cystic fibrosis ──────────────────────────────────────────────────────────────────────
  {
    id: 'cf',
    label: 'Cystic fibrosis',
    section: 26,
    sided: false,
    grades: [{ name: 'mild (FEV1 > 70 %)', severity: 0.33 }, { name: 'moderate (40–69 %)', severity: 0.67 }, { name: 'severe (< 40 %)', severity: 1 }],
    effects: [
      { key: 'raw', op: 'mul', v: [[0, 1], [0.33, 1.3], [0.67, 2], [1, 3]], src: "§26 row 'Inspiratory R': ×1.3/2.0/3.0 [ENG on §5]", tag: 'ENG' },
      { key: 'rawExp', op: 'set', v: [[0, 1.2], [0.33, 1.4], [1, 1.4]], src: "§26 row 'Expiratory ratio, τ': rawExpMult 1.4 [ENG]", tag: 'ENG' },
      { key: 'fSlow', op: 'set', v: [[0, 0], [0.33, 0.3], [0.67, 0.45], [1, 0.55]], src: "§26 row 'Expiratory ratio, τ': slow compartment 0.3/0.45/0.55 (§5; main §4.3) [ENG]", tag: 'ENG' },
      { key: 'tauSlowS', op: 'set', v: [[0, 0.5], [0.33, 1], [0.67, 1.5], [1, 2.5]], src: "§26 row 'Expiratory ratio, τ': τ_slow 1.0/1.5/2.5 s [ENG]", tag: 'ENG' },
      { key: 'crs', op: 'mul', v: [[0, 1], [0.33, 1], [0.67, 0.9], [1, 0.8]], src: "§26 row 'Compliance': ×1.0/0.9/0.8 (fibrosis + hyperinflation) [ENG]", tag: 'ENG' },
      { key: 'vqLow', op: 'add', v: [[0, 0], [0.33, 0.03], [0.67, 0.08], [1, 0.13]], src: "§26 row 'V/Q, shunt': low V/Q 0.05/0.10/0.15 − healthy 0.02 [ENG conversion]", tag: 'ENG' },
      { key: 'extraShunt', op: 'add', v: [[0, 0], [0.33, 0], [0.67, 0.03], [1, 0.08]], src: "§26 row 'V/Q, shunt': plugged-segment shunt 0/0.03/0.08 [TXT]/[ENG]", tag: 'ENG' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.33, 0.05], [0.67, 0.1], [1, 0.2]], src: "§26 row 'Dead space': +0.05/+0.10/+0.20 VD/VT [ENG]", tag: 'ENG' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.33, 1], [0.67, 1.2], [1, 2]], src: "§26 row 'PVR': ×1/1.2/2 (hypoxic PH, cor pulmonale; Miller 10e ch. 29 p. 883)", tag: 'TXT' },
    ],
    bands: {
      refSeverity: 0.67,
      rInsp: [20, 20],
      alphaDeg: [115, 130],
      spo2Fio2_021: [88, 94],
      src: "§26 rows 'Inspiratory R' ×2 → 20, 'Monitor signature' (alpha 115–130°, recurrent Ppeak spikes, SpO2 88–94 % on air)",
    },
    needs: ['7a', '7b', '7f', 'V'],
    pitfall: 'The airway problem in CF is secretions: suction and humidification do more than bronchodilators.',
  },
  // ── §27 Neuromuscular weakness (grade by VC mL/kg) ───────────────────────────────────────────
  {
    id: 'nmWeakness',
    label: 'Neuromuscular weakness',
    section: 27,
    sided: false,
    grades: [{ name: 'VC 40 mL/kg', severity: 0.25 }, { name: 'VC 30 mL/kg', severity: 0.5 }, { name: 'VC 20 mL/kg', severity: 0.75 }, { name: 'VC 15 mL/kg', severity: 1 }],
    effects: [
      { key: 'pMax', op: 'mul', v: [[0, 1], [0.25, 0.667], [0.5, 0.5], [0.75, 0.333], [1, 0.222]], src: "§27 row 'Maximal inspiratory pressure': 60/45/30/20 ÷ normal 90 (80–100) [ENG conversion] (Dellinger 5e ch. 61 p. 1027)", tag: 'TXT', q: 'Q88' },
      { key: 'ccw', op: 'mul', v: [[0, 1], [0.25, 1], [0.5, 0.9], [0.75, 0.8], [1, 0.7]], src: "§27 row 'Chest-wall compliance': ×1/0.9/0.8/0.7 (Dellinger 5e ch. 61 p. 1027)", tag: 'TXT' },
      { key: 'atel', op: 'add', v: [[0, 0], [0.25, 0.02], [1, 0.1]], src: "§27 row 'Cough effectiveness': retention → atel +0.02–0.10 over hours; recruitFrac 1.0 (§33) [ENG knots]", tag: 'TXT' },
      { key: 'co2Slope', op: 'mul', v: [[0, 1], [0.25, 1], [0.5, 0.7], [1, 0.7]], src: "§27 row 'Opioid/sedative sensitivity': CO2 slope ×0.7 in moderate–severe weakness [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.75,
      src: "§27: lung normal under PPV ('Ventilator': normal settings); signature is spontaneous (RR ↑, VT ↓, SpO2 normal until late); no numeric vent band",
    },
    needs: ['7b', '7f', 'V'],
    pitfall: 'SpO2 stays normal until very late (especially on O2): watch RR, VT, VC and PaCO2 instead.',
  },
  // ── §28 Diaphragmatic paralysis (unilateral default; bilateral values in src) ────────────────
  {
    id: 'diaphragmParalysis',
    label: 'Diaphragmatic paralysis (unilateral, e.g. interscalene block)',
    section: 28,
    sided: true,
    effects: [
      { key: 'pMax', op: 'mul', v: 0.73, src: "§28 row 'FVC / spontaneous VT capacity': unilateral ×0.73 (bilateral ×0.4–0.5 upright, supine ×0.7–0.8 more) (Urmey 1992)", tag: 'P' },
      { key: 'atel', op: 'add', v: 0.08, where: 'affected', src: "§28 row 'Basal atelectasis': unilateral +0.03–0.05 whole lung → 0.04 ÷ 0.5 = 0.08 of one lung (bilateral 0.08–0.12) [ENG]", tag: 'ENG' },
      { key: 'frc', op: 'mul', v: 0.9, src: "§28 row 'FRC': unilateral ×0.9 (bilateral ×0.75 supine) [TXT]/[ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 1,
      src: "§28 row 'Under PPV': invisible (ventilator does the work); spontaneous signature RR +3–6, SpO2 −1–3 % on air (unilateral)",
    },
    needs: ['7b', 'V'],
    pitfall: 'An interscalene block paralyses the hemidiaphragm in every patient, so avoid it when a 25 % fall in lung function cannot be tolerated.',
  },
  // ── §29 Pregnancy (respiratory; term = severity 1) ───────────────────────────────────────────
  {
    id: 'pregnancy',
    label: 'Pregnancy (respiratory)',
    section: 29,
    sided: false,
    grades: [{ name: 'T1 (≤ 13 wk)', severity: 0.33 }, { name: 'T2 (14–27 wk)', severity: 0.67 }, { name: 'term (38 wk)', severity: 1 }],
    effects: [
      { key: 'frc', op: 'mul', v: [[0, 1], [0.33, 1], [0.67, 0.9], [1, 0.8]], src: "main §1.4 FRC 1.0/0.9/0.80; §29 row 'FRC' ×0.8 at term (Stoelting 8e ch. 32 p. 698); supine ×0.9 not encoded", tag: 'TXT' },
      { key: 'ccw', op: 'mul', v: 0.7, src: "§29 row 'Chest-wall compliance': ×0.7 at term, lung unchanged; linear by trimester [ENG]", tag: 'VERIFY', q: 'Q89' },
      { key: 'crs', op: 'mul', v: 0.85, src: "§29 row 'Chest-wall compliance': Crs ×0.85 (system, from ccw ×0.7); §33 row 29", tag: 'VERIFY', q: 'Q89' },
      { key: 'tIt', op: 'set', v: 0.5, src: "§29 row 'Chest-wall compliance': tIt 0.5 (proposal; main §2.2 0.7 pending Q89)", tag: 'VERIFY', q: 'Q89' },
      { key: 'raw', op: 'mul', v: 1.2, src: "§29 row 'Airway': mucosal oedema, smaller ETT 6.0–7.0 → R ×1.2", tag: 'TXT' },
      { key: 'atel', op: 'add', v: 0.03, src: "§29 row 'Atelectasis at induction': main §4.1 ×1.5 → excess 0.5 × atelInd 0.06 = 0.03 (recruitFrac 1.0, §33) [ENG]", tag: 'ENG' },
      { key: 'pvr', op: 'mul', v: 0.8, src: "§29 row 'PVR': ×0.8 (falls in normal pregnancy)", tag: 'VERIFY' },
    ],
    bands: {
      refSeverity: 1,
      src: "§29 gives no numeric lung band; 'Ventilator under GA' targets EtCO2 28–32 (PaCO2 set point 30–32, main §1.4)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'An EtCO2 of 40 in a pregnant patient is hypoventilation: her normal is about 30.',
  },
  // ── §30 Neonatal RDS (needs the neonatal profile; multipliers are vs the size-scaled healthy lung) ─
  {
    id: 'neonatalRds',
    label: 'Neonatal respiratory distress syndrome (1.5 kg, 30 wk, moderate)',
    section: 30,
    sided: false,
    effects: [
      { key: 'crs', op: 'mul', v: 0.32, src: "§30 row 'Crs (per kg)': 0.4 mL/cmH2O/kg vs normal term ≈1–1.5 (1.25) [ENG conversion] (Miller 10e ch. 75 p. 2436)", tag: 'VERIFY', q: 'Q90' },
      { key: 'tIt', op: 'set', v: 0.15, src: "§30 row 'Chest-wall compliance': very compliant chest wall → tIt ≈ 0.1–0.2 (Miller 10e ch. 75 p. 2436)", tag: 'TXT' },
      { key: 'atel', op: 'add', v: 0.36, src: "§30 row 'Atelectasis / recruitability': atel 0.3–0.5 → 0.4 × recruitFrac 0.9 [ENG split]; re-collapse in seconds", tag: 'ENG', q: 'Q90' },
      { key: 'consol', op: 'add', v: 0.04, src: "§30 row 'Atelectasis / recruitability': 0.4 × (1 − 0.9) [ENG split]", tag: 'ENG', q: 'Q90' },
    ],
    bands: {
      refSeverity: 1,
      shunt: [0.2, 0.4],
      peep5to15: 'up',
      src: "§30 rows 'Shunt' intrapulmonary 0.2–0.4 (+ ductal 0–0.3), 'Atelectasis / recruitability' 0.9; reference is neonatal, not the adult 70 kg frame",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'Disconnection de-recruits a surfactant-deficient lung in seconds.',
  },
  // ── §31 COVID-type viral pneumonitis (L phenotype = 0.5, H = 1.0) ───────────────────────────
  {
    id: 'covidPneumonitis',
    label: 'COVID-type viral pneumonitis (L → H phenotype)',
    section: 31,
    sided: false,
    grades: [{ name: 'L phenotype', severity: 0.5 }, { name: 'H phenotype', severity: 1 }],
    effects: [
      { key: 'crs', op: 'mul', v: [[0, 1], [0.5, 0.909], [1, 0.636]], src: "§31 row 'Compliance': 50/35 ÷ 55 [ENG conversion] (Grasselli 2020: 41 [33–52])", tag: 'P' },
      { key: 'extraShunt', op: 'add', v: [[0, 0], [0.5, 0.3], [1, 0.35]], src: "§31 row 'Shunt': 0.3/0.35 (HPV loss, perfusion of non-aerated lung); recruitFrac 0.15/0.4 not split (no atel row)", tag: 'VERIFY', q: 'Q91' },
      { key: 'hpv', op: 'set', v: [[0, 0.5], [0.5, 0.1], [1, 0.3]], src: "§31 row 'HPV': 0.1/0.3 (dysregulated)", tag: 'VERIFY', q: 'Q91' },
      { key: 'vdAlv', op: 'add', v: [[0, 0], [0.5, 0.14], [1, 0.14]], src: "§31 row 'Dead space (microthrombi)': peFrac 0.1–0.3 → 0.2 × 0.7 (as §18) [ENG conversion] (Grasselli 2020)", tag: 'P' },
      { key: 'pvr', op: 'mul', v: [[0, 1], [0.5, 1.3], [1, 1.8]], src: "§31 row 'PVR': ×1.3/×1.8 (thrombosis + hypercapnia) [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 0.5,
      crs: [50, 50],
      gapPaEt: [10, 20],
      shunt: [0.3, 0.3],
      peep5to15: 'down',
      src: "§31 rows 'Compliance' L 50, 'Shunt' 0.3, 'Dead space' gap 10–20, 'Recruitability' (high PEEP in L overdistends and lowers CO)",
    },
    needs: ['7a', '7b', 'V'],
    pitfall: 'In the L phenotype oxygenation and mechanics disagree: high PEEP for a low P/F over-distends a compliant lung and drops CO.',
  },
  // ── §32 Smoke inhalation / CO (lower-airway component encoded; COHb, cyanide, supraglottic oedema are not lung keys) ─
  {
    id: 'smokeInhalation',
    label: 'Smoke inhalation and CO poisoning (moderate, lower-airway component)',
    section: 32,
    sided: false,
    effects: [
      { key: 'raw', op: 'mul', v: 2.51, src: "§32 'Lower-airway injury': §2 bronchospasm sev 0.3–0.6 → 0.45: ×(1+5·0.45^1.5) [ENG]; upper-airway ×5–20 not encoded (Q92)", tag: 'TXT', q: 'Q92' },
      { key: 'rawExp', op: 'set', v: 1.525, src: "§32 'Lower-airway injury' via §2 sev 0.45: 1.3 + 0.5·0.45 [ENG]", tag: 'ENG' },
      { key: 'fSlow', op: 'set', v: 0.335, src: "§32 'Lower-airway injury' via §2 sev 0.45: 0.2 + 0.3·0.45 [ENG]", tag: 'ENG' },
      { key: 'vqLow', op: 'add', v: 0.068, src: "§32 'Lower-airway injury' via §2 'Low-V/Q admixture' 0.15·0.45 [ENG]", tag: 'ENG' },
      { key: 'vdAlv', op: 'add', v: 0.09, src: "§32 'Lower-airway injury' via §2 'Dead space' 0.20·0.45 [ENG]", tag: 'ENG' },
    ],
    bands: {
      refSeverity: 1,
      spo2Fio2_10: [97, 100],
      src: "§32 row 'Monitor signature': SpO2 97–100 % falsely normal at COHb 25 % (FiO2 1.0 per 'Ventilator'); Dellinger 5e ch. 46 p. 736",
    },
    needs: ['7b', '7f', 'V'],
    pitfall: 'A normal SpO2 means nothing in CO poisoning: use co-oximetry.',
  },
];

/** Stage V's 39 ventilator-catalogue rows (packages/ventilator/src/pathology/catalogue.ts) → condition + severity (+ side). */
export const VENT_ROW_MAP: Readonly<Record<string, { id: string; severity: number; side?: 'L' | 'R' } | null>> = {
  'normal': null,
  'bronchospasm': { id: 'bronchospasm', severity: 0.5 }, // V Rinsp 30 ≈ §2 sev 0.5 (R 28)
  'anaphylaxis-bronchospasm': { id: 'anaphylaxis', severity: 0.6 }, // grade III
  'copd-gold-1-2': { id: 'copd', severity: 0.375 },
  'copd-gold-3-4': { id: 'copd', severity: 0.875 },
  'cystic-fibrosis': { id: 'cf', severity: 0.67 }, // moderate
  'tube-obstruction': { id: 'airwayObstruction', severity: 0.4 }, // V Rinsp 40 ≈ raw ×4.2
  'tracheal-obstruction': { id: 'airwayObstruction', severity: 0.25 }, // V Rinsp 30 ≈ raw ×3 (§25 fixed lesion; variable-lesion rawExp not encoded)
  'smoke-co': { id: 'smokeInhalation', severity: 1 },
  'ards-mild': { id: 'ards', severity: 0.33 },
  'ards-moderate': { id: 'ards', severity: 0.67 },
  'ards-severe-recruitable': { id: 'ards', severity: 1 }, // data carries population-mean recruitFrac 0.35; high recruiter 0.5 is in src
  'ards-severe-nonrecruitable': { id: 'ards', severity: 1 }, // low recruiter 0.15 is in src
  'fibrosis-ild': { id: 'ild', severity: 0.6 },
  'scleroderma': { id: 'ssc', severity: 1 }, // V row includes PH; catalogue §8 has PH off by default (stack 'ph' if wanted)
  'chest-wall-restriction': { id: 'chestWall', severity: 0.67 }, // Cobb 70–100°
  'obesity-ohs': { id: 'obesity', severity: 1 }, // BMI ≥ 40; OHS flag not encoded
  'pneumonia-lobar': { id: 'pneumonia', severity: 0.4 }, // one lower lobe; side chosen at apply time
  'atelectasis': null, // V = post-induction atelectasis = main §4.1 dynamic atelInd, not the §12 lobar-collapse preset
  'oedema-cardiogenic': { id: 'pulmOedema', severity: 1 },
  'oedema-noncardiogenic': { id: 'pulmOedema', severity: 1 }, // cause switch not encoded; non-cardiogenic values are in src
  'aspiration': { id: 'aspiration', severity: 1, side: 'R' },
  'covid-pneumonitis': { id: 'covidPneumonitis', severity: 1 }, // V Crs 40 closer to H phenotype (35)
  'pulmonary-hypertension': { id: 'ph', severity: 0.67 }, // V PVR ×3 ≈ moderate 5 WU
  'pe-massive': { id: 'pe', severity: 1 },
  'pe-submassive': { id: 'pe', severity: 0.67 },
  'fat-embolism': { id: 'fatEmbolism', severity: 0.67 }, // BCIS grade 2
  'air-embolism': { id: 'vae', severity: 1 },
  'pleural-effusion': { id: 'effusion', severity: 0.5 }, // 1.5 L catalogue default
  'pneumothorax-simple': { id: 'ptxSimple', severity: 0.3 },
  'pneumothorax-tension': { id: 'ptxTension', severity: 0.8 },
  'haemothorax': { id: 'haemothorax', severity: 0.5 },
  'one-lung-ventilation': { id: 'olv', severity: 1, side: 'L' },
  'endobronchial': { id: 'endobronchial', severity: 1, side: 'L' },
  'bronchopleural-fistula': { id: 'bpf', severity: 0.5 },
  'neuromuscular-weakness': { id: 'nmWeakness', severity: 0.75 }, // VC 20 mL/kg
  'diaphragm-paralysis': { id: 'diaphragmParalysis', severity: 1 }, // V row is BILATERAL; data default is unilateral
  'pregnancy': { id: 'pregnancy', severity: 1 },
  'neonatal-rds': { id: 'neonatalRds', severity: 1 },
};
