// R56 clinical glossary: engine key → clinical label, full name, unit, adult normal range (research/11-capability-inventory-
// and-glossary.md §5, 294 entries, generated 2026-09-28 by the Stage 9 plan writer from the workspace research file; edits
// go HERE and are reviewed by Ali). `keys` are console truth paths; `#` = side index (0 L, 1 R), `*`/`<id>` = any segment.
// Entries without keys are planned labels (R57/R58/R59) that the UI already uses for placeholders.
export interface GlossaryEntry {
  n: number;
  /** research/11 section (5.1 monitor … 5.15 obstetric). */
  s: string;
  keys: string[];
  label: string;
  name: string;
  unit: string;
  normal: string;
  /** Child / pregnancy values where they differ. */
  other?: string;
  convention?: string;
}

export const GLOSSARY: readonly GlossaryEntry[] = [
  { n: 1, s: '5.1', keys: ["mon.hr"], label: "HR", name: "Heart rate (ECG)", unit: "bpm", normal: "60–100", other: "child 80–120; neonate 100–160 / Preg +10–20", convention: "all vendors" },
  { n: 2, s: '5.1', keys: ["mon.pr"], label: "PR", name: "Pulse rate (from SpO2 or ART; name the source)", unit: "bpm", normal: "= HR (pulse deficit in AF)", other: "as HR", convention: "GE/Mr/Sa \"PR\"; Phil \"Pulse\"" },
  { n: 3, s: '5.1', keys: ["mon.spo2"], label: "SpO₂", name: "Peripheral O2 saturation (pulse oximetry)", unit: "%", normal: "95–100", other: "neonate pre-ductal ≥ 90 after 10 min", convention: "all" },
  { n: 4, s: '5.1', keys: ["mon.pi"], label: "PI", name: "Perfusion index (pulsatile/non-pulsatile IR absorbance)", unit: "%", normal: "typical 1–10 (device range 0.02–20)", convention: "Masimo/Mr/Sa \"PI\"; Phil \"Perf\"" },
  { n: 5, s: '5.1', keys: ["mon.abpSys"], label: "ART S", name: "Invasive arterial pressure, systolic", unit: "mmHg", normal: "90–140", other: "child 90–110 / Preg −5–10 mid-gestation", convention: "GE/Mr/Dr/NK/Sa \"ART\"; Phil \"ABP\"" },
  { n: 6, s: '5.1', keys: ["mon.abpDia"], label: "ART D", name: "Invasive arterial pressure, diastolic", unit: "mmHg", normal: "60–90", other: "child 55–70", convention: "as 5" },
  { n: 7, s: '5.1', keys: ["mon.abpMean"], label: "ART M (MAP)", name: "Mean arterial pressure (invasive)", unit: "mmHg", normal: "70–105", other: "child 60–75 / Preg 75–90", convention: "as 5; \"MAP\" in textbooks" },
  { n: 8, s: '5.1', keys: ["mon.cvpMean"], label: "CVP", name: "Central venous pressure (mean)", unit: "mmHg", normal: "2–8 (spontaneous)", convention: "all" },
  { n: 9, s: '5.1', keys: ["mon.papSys"], label: "PAP S", name: "Pulmonary artery pressure, systolic", unit: "mmHg", normal: "15–30", convention: "Phil \"PAP\"; GE/Mr \"PA\" (usage)" },
  { n: 10, s: '5.1', keys: ["mon.papDia"], label: "PAP D", name: "Pulmonary artery pressure, diastolic", unit: "mmHg", normal: "4–12", convention: "as 9" },
  { n: 11, s: '5.1', keys: ["mon.papMean"], label: "mPAP", name: "Mean pulmonary artery pressure", unit: "mmHg", normal: "10–20 (PH > 20, ESC/ERS 2022)", convention: "textbooks \"mPAP\"" },
  { n: 12, s: '5.1', keys: ["ev.state.values.pawp"], label: "PAWP", name: "Pulmonary artery wedge (occlusion) pressure", unit: "mmHg", normal: "6–12", convention: "\"PCWP\" common alias; Phil \"PAWP\"" },
  { n: 13, s: '5.1', keys: ["mon.nibpSys", "mon.nibpDia", "mon.nibpMean"], label: "NIBP S/D/M", name: "Non-invasive (oscillometric) blood pressure", unit: "mmHg", normal: "as ART", other: "as ART", convention: "GE/Mr/NK/Sa \"NIBP\"; Phil/Dr \"NBP\"" },
  { n: 14, s: '5.1', keys: ["ev.nibp.cuffMmHg"], label: "Cuff", name: "NIBP cuff pressure during inflation", unit: "mmHg", normal: "—", convention: "Phil shows cuff pressure in the tile" },
  { n: 15, s: '5.1', keys: ["mon.etco2"], label: "EtCO₂", name: "End-tidal CO2 partial pressure", unit: "mmHg", normal: "35–45 (PaCO2 − 2 to 5)", other: "Preg 28–32", convention: "GE/Mr/Sa \"EtCO₂\"; Phil \"etCO₂\"" },
  { n: 16, s: '5.1', keys: ["mon.imco2"], label: "FiCO₂", name: "Inspired (minimum) CO2", unit: "mmHg", normal: "0 (< 2)", convention: "GE/Mr/Sa \"FiCO₂\"; Phil \"imCO₂\"" },
  { n: 17, s: '5.1', keys: ["mon.awrr"], label: "awRR", name: "Airway respiratory rate (from the CO2/flow signal)", unit: "/min", normal: "12–20", other: "child 20–30; neonate 30–60", convention: "Phil/Mr \"awRR\"; Sa \"AWRR\"" },
  { n: 18, s: '5.1', keys: ["mon.rr"], label: "RR", name: "Respiratory rate (impedance)", unit: "/min (skins may show rpm)", normal: "12–20", other: "as 17", convention: "all \"RR\"; unit rpm (GE/Mr) or /min" },
  { n: 19, s: '5.1', keys: ["mon.tempCore"], label: "T1 (Tcore)", name: "Temperature 1 — core (oesophageal probe)", unit: "°C", normal: "36.5–37.5", convention: "GE/Mr/Sa \"T1\"; Phil \"Tcore\"/\"Tesoph\"" },
  { n: 20, s: '5.1', keys: ["mon.tempSite"], label: "T2 (site)", name: "Temperature 2 at the chosen site: Tnaso, Ttymp, Tblad, Trect, Taxil", unit: "°C", normal: "site-dependent (axilla −0.5 to −1)", convention: "GE/Mr/Sa \"T2\"; Phil by site" },
  { n: 21, s: '5.1', keys: [], label: "ΔT (TD)", name: "Core–site temperature difference", unit: "°C", normal: "< 2", convention: "Sa \"DT\"; Mr \"TD\"" },
  { n: 22, s: '5.1', keys: ["mon.stII"], label: "ST-II", name: "ST-segment deviation, lead II (J + 60/80 ms)", unit: "mm or mV (1 mm = 0.1 mV)", normal: "±0.1 mV (≥ 0.1 mV depression = ischaemia)", convention: "Phil \"ST-II\"; GE/Mr \"ST II\"" },
  { n: 23, s: '5.1', keys: ["mon.qtc"], label: "QTc", name: "Corrected QT interval (state the formula: Bazett/Fridericia)", unit: "ms", normal: "< 450 M, < 460 F (> 500 high risk)", other: "child < 450", convention: "Phil \"QTc\"" },
  { n: 24, s: '5.1', keys: ["mon.tofCount"], label: "TOF count", name: "Train-of-four count", unit: "0–4", normal: "4 (no block)", convention: "Phil \"TOF-Cnt\"; GE NMT \"Count\"" },
  { n: 25, s: '5.1', keys: ["mon.tofRatio"], label: "TOFR", name: "Train-of-four ratio T4/T1", unit: "%", normal: "≥ 90 % = adequate recovery", convention: "Phil \"TOF-Ratio\"; GE \"TOF%\"" },
  { n: 26, s: '5.1', keys: ["mon.ptc"], label: "PTC", name: "Post-tetanic count", unit: "0–20", normal: "n/a (used at TOF 0)", convention: "Phil/GE \"PTC\"" },
  { n: 27, s: '5.1', keys: ["mon.di"], label: "DoA index (BIS/qCON/PSI/BFI per skin)", name: "Processed-EEG depth-of-anaesthesia index", unit: "0–100", normal: "awake > 90; GA 40–60", convention: "Medtronic \"BIS\"; GE \"SE/RE\" (Entropy); Masimo \"PSi\"; Sa \"BFI\"" },
  { n: 28, s: '5.1', keys: ["mon.sr"], label: "SR", name: "Burst-suppression ratio", unit: "%", normal: "0", convention: "BIS \"SR\"; Sa \"BS%\"" },
  { n: 29, s: '5.1', keys: ["mon.mac"], label: "MAC", name: "Minimum alveolar concentration multiple (end-tidal, age-adjusted, Σ agents incl. N2O)", unit: "MAC", normal: "GA 0.7–1.3; MAC-awake 0.3–0.4", other: "Preg 1 MAC is 25–40 % lower", convention: "Phil/GE/Dr \"MAC\" (agent module)" },
  { n: 30, s: '5.1', keys: ["mon.etAa"], label: "EtAA (EtSEV/EtISO/EtDES)", name: "End-tidal anaesthetic agent concentration", unit: "%", normal: "agent-specific (1 MAC at 40 y: sevo 2.0, iso 1.15, des 6.0)", other: "child MAC higher", convention: "Phil \"etSEV\"; GE \"EtSev\" (usage)" },
  { n: 31, s: '5.1', keys: ["mon.icpMean"], label: "ICP", name: "Intracranial pressure (mean)", unit: "mmHg", normal: "5–15 (treat > 22, BTF)", other: "infant 1.5–6; child 3–7", convention: "all" },
  { n: 32, s: '5.1', keys: ["mon.cpp"], label: "CPP", name: "Cerebral perfusion pressure = MAP − ICP", unit: "mmHg", normal: "60–80 (TBI target 60–70)", other: "child 40–50 (age-dependent)", convention: "Phil/Sa \"CPP\" with ICP" },
  { n: 33, s: '5.1', keys: ["mon.pbto2"], label: "PbtO₂", name: "Brain tissue O2 tension", unit: "mmHg", normal: "20–35 (treat < 20)", convention: "Licox \"PbtO₂\"" },
  { n: 34, s: '5.1', keys: ["mon.uop"], label: "UO", name: "Urine output (rolling 60 min)", unit: "mL/h (and mL/kg/h)", normal: "≥ 0.5 mL/kg/h", other: "child ≥ 1; infant ≥ 1–2 mL/kg/h", convention: "ICU charts \"UO\"" },
  { n: 35, s: '5.1', keys: [], label: "PPV", name: "Pulse-pressure variation", unit: "%", normal: "< 13 % (fluid-responsive > 13 on VT ≥ 8 mL/kg)", convention: "Phil/GE/Mr \"PPV\"" },
  { n: 36, s: '5.1', keys: [], label: "SVV", name: "Stroke-volume variation", unit: "%", normal: "< 10–13 %", convention: "pulse-contour devices" },
  { n: 37, s: '5.1', keys: ["mon.hr"], label: "HR source", name: "Where HR comes from (ECG / ART / SpO2)", unit: "—", normal: "—", convention: "Sa AUTO relabels to \"PR\"" },
  { n: 38, s: '5.2', keys: [], label: "I, II, III, aVR, aVL, aVF, V1–V6", name: "ECG leads", unit: "mV", normal: "", convention: "all" },
  { n: 39, s: '5.2', keys: [], label: "ART", name: "Arterial pressure waveform", unit: "mmHg", normal: "", convention: "GE/Mr/Dr/Sa \"ART\"; Phil \"ABP\"" },
  { n: 40, s: '5.2', keys: [], label: "CVP", name: "Central venous pressure waveform", unit: "mmHg", normal: "", convention: "all" },
  { n: 41, s: '5.2', keys: [], label: "PAP", name: "Pulmonary artery pressure waveform (wedge trace when inflated)", unit: "mmHg", normal: "", convention: "Phil \"PAP\"; GE/Mr \"PA\"" },
  { n: 42, s: '5.2', keys: [], label: "Pleth", name: "Plethysmogram (SpO2)", unit: "a.u.", normal: "", convention: "all" },
  { n: 43, s: '5.2', keys: [], label: "CO₂", name: "Capnogram", unit: "mmHg", normal: "", convention: "all" },
  { n: 44, s: '5.2', keys: [], label: "Resp", name: "Impedance respiration", unit: "a.u.", normal: "", convention: "all \"RESP\"" },
  { n: 45, s: '5.2', keys: [], label: "ICP", name: "ICP waveform (P1/P2/P3)", unit: "mmHg", normal: "", convention: "all" },
  { n: 46, s: '5.2', keys: [], label: "LVP", name: "Left-ventricular pressure (teaching)", unit: "mmHg", normal: "", convention: "Sa \"LVP\"" },
  { n: 47, s: '5.2', keys: [], label: "LV volume", name: "Left-ventricular volume (PV-loop teaching)", unit: "mL", normal: "", convention: "textbooks" },
  { n: 48, s: '5.2', keys: [], label: "LAP, RAP, RVP", name: "Left atrial, right atrial, right ventricular pressure", unit: "mmHg", normal: "", convention: "Sa \"LAP/RAP/RVP\"" },
  { n: 49, s: '5.2', keys: [], label: "PAP (true)", name: "Pulmonary artery pressure without the catheter transfer function (teaching)", unit: "mmHg", normal: "", convention: "—" },
  { n: 50, s: '5.2', keys: [], label: "Paw, Flow, Vol", name: "Airway pressure, flow, volume (anaesthesia-workstation lanes)", unit: "cmH₂O, L/min, mL", normal: "", convention: "Ham/Dräger \"Paw/Flow/Vol\"" },
  { n: 51, s: '5.3', keys: ["ev.circ.co"], label: "CO", name: "Cardiac output", unit: "L/min", normal: "4–8", other: "child ≈ 2.5–3.5 / Preg +30–50 %", convention: "all (\"C.O.\" Phil)" },
  { n: 52, s: '5.3', keys: [], label: "CI", name: "Cardiac index = CO/BSA", unit: "L/min/m²", normal: "2.5–4.0", convention: "all" },
  { n: 53, s: '5.3', keys: ["ev.circ.sv"], label: "SV", name: "Stroke volume (LV)", unit: "mL", normal: "60–100", convention: "all" },
  { n: 54, s: '5.3', keys: [], label: "SVI", name: "Stroke volume index", unit: "mL/m²", normal: "33–47", convention: "all" },
  { n: 55, s: '5.3', keys: ["ev.circ.svRv"], label: "RVSV", name: "Right-ventricular stroke volume", unit: "mL", normal: "= SV", convention: "textbooks" },
  { n: 56, s: '5.3', keys: ["ev.circ.ef"], label: "LVEF", name: "Left-ventricular ejection fraction", unit: "%", normal: "55–70 (≥ 50)", convention: "echo" },
  { n: 57, s: '5.3', keys: ["ev.circ.lvedv"], label: "LVEDV", name: "LV end-diastolic volume", unit: "mL", normal: "65–150", convention: "echo" },
  { n: 58, s: '5.3', keys: ["ev.circ.lvesv"], label: "LVESV", name: "LV end-systolic volume", unit: "mL", normal: "20–60", convention: "echo" },
  { n: 59, s: '5.3', keys: ["ev.circ.lvedp"], label: "LVEDP", name: "LV end-diastolic pressure", unit: "mmHg", normal: "4–12", convention: "cath lab" },
  { n: 60, s: '5.3', keys: ["ev.circ.lvsp"], label: "LVSP", name: "LV peak systolic pressure", unit: "mmHg", normal: "90–140 (= SBP without AS)", convention: "cath lab" },
  { n: 61, s: '5.3', keys: ["ev.circ.svr"], label: "SVR", name: "Systemic vascular resistance", unit: "dyn·s·cm⁻⁵ (WU alternative)", normal: "800–1,200 (10–15 WU)", other: "Preg −25–30 %", convention: "all" },
  { n: 62, s: '5.3', keys: [], label: "SVRI", name: "SVR index", unit: "dyn·s·cm⁻⁵·m²", normal: "1,970–2,390", convention: "PAC" },
  { n: 63, s: '5.3', keys: ["ev.circ.pvr"], label: "PVR", name: "Pulmonary vascular resistance", unit: "dyn·s·cm⁻⁵ (WU)", normal: "40–160 (< 2 WU)", other: "Preg ×0.8", convention: "all" },
  { n: 64, s: '5.3', keys: ["ev.circ.pmsf"], label: "Pmsf", name: "Mean systemic filling pressure", unit: "mmHg", normal: "≈ 7–20 (method-dependent)", convention: "Guyton; physiology texts" },
  { n: 65, s: '5.3', keys: ["ev.circ.cpp"], label: "CoPP", name: "Coronary perfusion pressure = aortic diastolic − LVEDP", unit: "mmHg", normal: "50–80; CPR ≥ 15–20 for ROSC (Paradis)", convention: "textbooks write \"CPP\", which collides with 32: use CoPP" },
  { n: 66, s: '5.3', keys: ["ev.circ.supplyDemand"], label: "Myocardial O2 supply/demand", name: "Coronary supply/demand ratio (EVR-like, DPTI/TTI analogue)", unit: "ratio", normal: "> 1 (EVR ≥ 0.7 in Buckberg's terms)", convention: "Buckberg EVR" },
  { n: 67, s: '5.3', keys: ["ev.circ.kIsch"], label: "Ischaemia factor", name: "Fraction of normal contractility left by ischaemia (model)", unit: "0–1", normal: "1", convention: "engine-only; keep as an instructor label" },
  { n: 68, s: '5.3', keys: ["hemo.circ.p.rSys"], label: "SVR (model)", name: "Model systemic resistance (the parameter behind 61)", unit: "mmHg·s/mL", normal: "≈ 0.85–1.05", convention: "engine" },
  { n: 69, s: '5.3', keys: ["hemo.circ.p.eesLv", "hemo.circ.p.eesRv"], label: "Ees LV / Ees RV", name: "End-systolic elastance (contractility)", unit: "mmHg/mL", normal: "LV 2–3; RV 0.5–0.8", convention: "Suga/Sagawa" },
  { n: 70, s: '5.3', keys: ["hemo.circ.p.cArt"], label: "Ca (arterial compliance)", name: "Total arterial compliance", unit: "mL/mmHg", normal: "1.2–2.0", other: "elderly ≈ 0.6–0.9", convention: "physiology texts" },
  { n: 71, s: '5.3', keys: ["hemo.circ.p.v0Sv", "hemo.circ.p.cSv"], label: "Vu, Cv", name: "Unstressed venous volume; venous compliance", unit: "mL; mL/mmHg", normal: "Vu ≈ 70 % of blood volume; Cv 100–130", convention: "Guyton/Magder" },
  { n: 72, s: '5.3', keys: ["hemo.circ.p.av.eroa", "hemo.circ.p.mv.eroa", "hemo.circ.p.tv.eroa", "hemo.circ.p.pv.eroa"], label: "EROA", name: "Effective regurgitant orifice area (per valve)", unit: "cm²", normal: "0", convention: "echo (ASE)" },
  { n: 73, s: '5.3', keys: ["hemo.circ.p.av.r"], label: "Valve resistance", name: "Model valve resistance (AS/MS: use AVA/MVA and mean gradient)", unit: "mmHg·s/mL", normal: "—", convention: "echo reports AVA (cm²) and mean gradient (mmHg)" },
  { n: 74, s: '5.3', keys: ["hemo.circOut.pAo"], label: "Aortic pressure", name: "Central aortic pressure", unit: "mmHg", normal: "≈ radial − 0–10 systolic", convention: "textbooks" },
  { n: 75, s: '5.3', keys: ["hemo.circOut.pRad"], label: "Radial pressure", name: "Radial artery pressure (the ART site)", unit: "mmHg", normal: "as ART", convention: "—" },
  { n: 76, s: '5.3', keys: ["hemo.circOut.pLa"], label: "LAP", name: "Left atrial pressure", unit: "mmHg", normal: "4–12", convention: "Sa \"LAP\"" },
  { n: 77, s: '5.3', keys: ["hemo.circOut.pRa"], label: "RAP", name: "Right atrial pressure", unit: "mmHg", normal: "2–8 (≈ CVP)", convention: "Sa \"RAP\"" },
  { n: 78, s: '5.3', keys: ["hemo.circOut.pRv"], label: "RVP", name: "Right-ventricular pressure", unit: "mmHg", normal: "15–30 / 0–8", convention: "Sa \"RVP\"" },
  { n: 79, s: '5.3', keys: ["hemo.circOut.pLv"], label: "LVP", name: "Left-ventricular pressure", unit: "mmHg", normal: "90–140 / 4–12", convention: "Sa \"LVP\"" },
  { n: 80, s: '5.3', keys: ["hemo.circOut.pPa", "hemo.circOut.pPaRoot"], label: "PAP (model)", name: "Pulmonary artery pressure (distal / root)", unit: "mmHg", normal: "as 9–11", convention: "—" },
  { n: 81, s: '5.3', keys: ["hemo.circOut.pPv"], label: "Ppv (≈ PAWP)", name: "Pulmonary venous pressure", unit: "mmHg", normal: "6–12", convention: "West zones" },
  { n: 82, s: '5.3', keys: ["hemo.circOut.pSv"], label: "Psv", name: "Systemic venous (reservoir) pressure (≈ Pmsf at no flow)", unit: "mmHg", normal: "≈ 10–15", convention: "Guyton" },
  { n: 83, s: '5.3', keys: ["hemo.circOut.pIt"], label: "Ppl (pleural)", name: "Intrathoracic (pleural) pressure", unit: "mmHg (show cmH₂O too)", normal: "−3 to −8 cmH₂O (end-exp, spont); + under PPV", convention: "West" },
  { n: 84, s: '5.3', keys: ["hemo.circOut.pPeri"], label: "Ppericardial", name: "Pericardial pressure", unit: "mmHg", normal: "≈ 0 to −3 (tamponade ≥ RAP)", convention: "Barash" },
  { n: 85, s: '5.3', keys: ["hemo.circOut.qSys", "hemo.circOut.qVr"], label: "Q̇ (flows)", name: "Systemic flow, venous return, valve flows", unit: "mL/s", normal: "—", convention: "engine (teaching)" },
  { n: 86, s: '5.3', keys: ["hemo.circOut.qLungL", "hemo.circOut.qLungR"], label: "Q̇ L/R lung", name: "Pulmonary blood flow per lung", unit: "mL/s (show % of CO)", normal: "L 45 %, R 55 % supine", convention: "West" },
  { n: 87, s: '5.3', keys: ["hemo.circ.baro.set"], label: "Baroreflex set point", name: "MAP the baroreflex defends", unit: "mmHg", normal: "85–95 awake; GA −10–20 %", convention: "physiology" },
  { n: 88, s: '5.3', keys: ["hemo.circ.baro.es", "hemo.circ.baro.ev"], label: "Sympathetic / vagal tone", name: "Baroreflex efferent activity (model units)", unit: "a.u.", normal: "—", convention: "engine (instructor)" },
  { n: 89, s: '5.3', keys: ["hemo.circ.ext.drug.*"], label: "Drug effect on SVR / Ees / venous tone / reflex gain / HR", name: "Pharmacodynamic multipliers", unit: "×", normal: "1", convention: "engine (instructor)" },
  { n: 90, s: '5.3', keys: ["ev.state.values.contractility", "ev.state.values.volumeStatus"], label: "Contractility (×), Volume status (×)", name: "MANUAL instructor inputs", unit: "× baseline", normal: "1", convention: "instructor only" },
  { n: 91, s: '5.3', keys: ["ev.beat.mech.lvetMs"], label: "LVET", name: "Left-ventricular ejection time", unit: "ms", normal: "250–320 (HR-dependent)", convention: "Weissler" },
  { n: 92, s: '5.3', keys: ["ev.circ.iabp.augmentation"], label: "Diastolic augmentation", name: "IABP augmented diastolic pressure", unit: "mmHg", normal: "> unassisted SBP", convention: "IABP consoles \"Aug\"" },
  { n: 93, s: '5.3', keys: [], label: "SPV / dSBP", name: "Systolic pressure variation", unit: "mmHg", normal: "< 10", convention: "anaesthesia texts" },
  { n: 94, s: '5.3', keys: [], label: "CPO", name: "Cardiac power output = MAP·CO/451", unit: "W", normal: "≈ 1.0 (shock < 0.6)", convention: "cardiogenic-shock texts" },
  { n: 95, s: '5.4', keys: ["blood.core.o2.cao2"], label: "CaO₂", name: "Arterial O2 content", unit: "mL/dL (engine mL/L ÷ 10)", normal: "18–21 mL/dL", other: "Preg lower (Hb 11.5)", convention: "textbooks" },
  { n: 96, s: '5.4', keys: ["resp.lung.o2.cv"], label: "CvO₂", name: "Mixed-venous O2 content", unit: "mL/dL (engine mL/L)", normal: "14–16", convention: "textbooks" },
  { n: 97, s: '5.4', keys: ["blood.core.o2.do2"], label: "DO₂", name: "O2 delivery = CO·CaO2", unit: "mL/min (DO2I mL/min/m²)", normal: "950–1,150 (DO2I 500–600)", convention: "textbooks" },
  { n: 98, s: '5.4', keys: ["blood.core.o2.vo2", "resp.pat.vo2"], label: "VO₂", name: "O2 consumption", unit: "mL/min", normal: "200–250 (3.5 mL/kg/min)", other: "child 5–7 mL/kg/min / Preg +20–30 %", convention: "textbooks" },
  { n: 99, s: '5.4', keys: ["blood.core.o2.er"], label: "O₂ER", name: "O2 extraction ratio = VO2/DO2", unit: "%", normal: "22–30", convention: "textbooks" },
  { n: 100, s: '5.4', keys: ["blood.core.o2.svo2"], label: "SvO₂", name: "Mixed-venous O2 saturation", unit: "% (engine fraction)", normal: "65–75", convention: "PAC oximetry (\"SvO₂\" all vendors)" },
  { n: 101, s: '5.4', keys: [], label: "ScvO₂", name: "Central-venous O2 saturation", unit: "%", normal: "70–80 (SvO2 + 2–5)", convention: "sepsis bundles" },
  { n: 102, s: '5.4', keys: ["blood.core.o2.deficit"], label: "O₂ debt", name: "Accumulated O2 deficit (model)", unit: "mL", normal: "0", convention: "shock physiology" },
  { n: 103, s: '5.4', keys: ["blood.core.odc.dpgMmolL"], label: "2,3-DPG", name: "Red-cell 2,3-diphosphoglycerate", unit: "mmol/L", normal: "4–5", convention: "textbooks" },
  { n: 104, s: '5.4', keys: [], label: "P50", name: "PO2 at 50 % saturation", unit: "mmHg", normal: "26–27", other: "Preg ≈ 30; neonate ≈ 19", convention: "textbooks" },
  { n: 105, s: '5.5', keys: ["resp.o2.pao2"], label: "PaO₂", name: "Arterial O2 tension", unit: "mmHg", normal: "80–100 on air (≈ 100 − age/3)", other: "Preg 100–105", convention: "textbooks" },
  { n: 106, s: '5.5', keys: ["resp.o2.sa"], label: "SaO₂", name: "Arterial O2 saturation (functional)", unit: "%", normal: "95–99", convention: "textbooks" },
  { n: 107, s: '5.5', keys: ["resp.o2.fa"], label: "FAO₂", name: "Alveolar O2 fraction", unit: "%", normal: "≈ 14 on air", convention: "West" },
  { n: 108, s: '5.5', keys: [], label: "PAO₂", name: "Alveolar O2 tension (alveolar gas equation)", unit: "mmHg", normal: "≈ 100 on air", convention: "West" },
  { n: 109, s: '5.5', keys: [], label: "A–a DO₂", name: "Alveolar–arterial O2 gradient", unit: "mmHg", normal: "5–15 on air (≈ age/4 + 4)", convention: "West" },
  { n: 110, s: '5.5', keys: [], label: "P/F", name: "PaO2/FiO2 ratio", unit: "mmHg", normal: "> 400 (ARDS ≤ 300, Berlin)", convention: "ARDSnet/Berlin" },
  { n: 111, s: '5.5', keys: ["resp.co2.pf"], label: "PaCO₂", name: "Arterial CO2 tension", unit: "mmHg", normal: "35–45", other: "Preg 28–32", convention: "textbooks" },
  { n: 112, s: '5.5', keys: ["resp.etco2", "ev.breath.etco2True"], label: "EtCO₂ (true)", name: "End-tidal CO2 before the sampler (truth)", unit: "mmHg", normal: "35–45", other: "Preg 28–32", convention: "—" },
  { n: 113, s: '5.5', keys: ["resp.lung.co2.pv"], label: "PvCO₂", name: "Mixed-venous CO2 tension", unit: "mmHg", normal: "41–51 (PaCO2 + 4–6)", convention: "textbooks" },
  { n: 114, s: '5.5', keys: ["resp.lung.co2.g"], label: "EtCO₂/PaCO₂", name: "End-tidal to arterial CO2 ratio", unit: "—", normal: "0.9–1.0", convention: "—" },
  { n: 115, s: '5.5', keys: [], label: "Pa–EtCO₂", name: "Arterial–end-tidal CO2 gradient", unit: "mmHg", normal: "2–5", convention: "Miller (capnography)" },
  { n: 116, s: '5.5', keys: ["resp.lung.co2.faCo2"], label: "FACO₂", name: "Alveolar CO2 fraction", unit: "%", normal: "≈ 5.6", convention: "West" },
  { n: 117, s: '5.5', keys: ["resp.lung.co2.riseIII"], label: "Phase III slope", name: "Capnogram alveolar-plateau rise", unit: "mmHg (per breath) or mmHg/s", normal: "< 2–3 mmHg", convention: "capnography texts" },
  { n: 118, s: '5.5', keys: ["resp.lung.co2.e"], label: "CO₂ elimination efficiency", name: "Model CO2-elimination factor", unit: "—", normal: "1", convention: "engine" },
  { n: 119, s: '5.5', keys: ["resp.shunt", "ev.lungState.shunt"], label: "Qs/Qt (shunt)", name: "Shunt fraction", unit: "%", normal: "2–5 awake; 8–10 under GA", other: "neonate 5–10", convention: "textbooks" },
  { n: 120, s: '5.5', keys: ["ev.lungState.vqAdmixture", "resp.lung.lp.side.#.vqLow"], label: "Venous admixture (low V/Q)", name: "FiO2-responsive admixture from low-V/Q units", unit: "%", normal: "≈ 2", convention: "West" },
  { n: 121, s: '5.5', keys: ["resp.pat.vco2"], label: "VCO₂", name: "CO2 production", unit: "mL/min", normal: "≈ 200 (RQ 0.8)", other: "child 4–5 mL/kg/min / Preg ↑", convention: "textbooks" },
  { n: 122, s: '5.5', keys: ["resp.vaLpm"], label: "V̇A", name: "Alveolar ventilation", unit: "L/min", normal: "4–5", other: "Preg ↑ 50–70 %", convention: "West" },
  { n: 123, s: '5.5', keys: ["resp.spont.ve"], label: "V̇E (MV)", name: "Minute ventilation (spontaneous)", unit: "L/min", normal: "5–8", other: "Preg +40–50 %", convention: "all \"MV\"" },
  { n: 124, s: '5.5', keys: ["resp.spont.rr"], label: "RR (spont)", name: "Spontaneous respiratory rate (truth)", unit: "/min", normal: "12–20", other: "child 20–30", convention: "—" },
  { n: 125, s: '5.5', keys: ["resp.spont.vt", "ev.breath.vtMl", "resp.mechanics.vt"], label: "VT", name: "Tidal volume", unit: "mL (and mL/kg PBW)", normal: "6–8 mL/kg PBW", other: "Preg ↑ 30–40 %", convention: "all" },
  { n: 126, s: '5.5', keys: ["resp.spont.paco2Set"], label: "PaCO₂ set point", name: "Chemoreflex PaCO2 target", unit: "mmHg", normal: "≈ 40", other: "Preg 30–32", convention: "physiology" },
  { n: 127, s: '5.5', keys: ["resp.spont.fatigue"], label: "Respiratory muscle fatigue", name: "Fatigue factor (model)", unit: "0–1", normal: "1 (none)", convention: "engine" },
  { n: 128, s: '5.5', keys: ["ev.breath.tiS", "ev.breath.teS"], label: "Ti, Te", name: "Inspiratory and expiratory time", unit: "s", normal: "Ti 1–1.5; I:E 1:2", convention: "Ham \"Ti\"; \"I:E\"" },
  { n: 129, s: '5.5', keys: ["resp.driver.vent.rr", "resp.driver.vent.vt", "resp.driver.vent.peep", "resp.driver.vent.ie"], label: "f set, VT set, PEEP, I:E", name: "Ventilator settings (engine VCV)", unit: "/min, mL, cmH₂O, ratio", normal: "—", convention: "Ham/Dräger" },
  { n: 130, s: '5.5', keys: ["l1.coupled.fio2", "ev.state.values.fio2"], label: "FiO₂", name: "Inspired O2 fraction", unit: "% (engine fraction)", normal: "21 % air", convention: "all" },
  { n: 131, s: '5.5', keys: ["resp.driver.fico2"], label: "FiCO₂ (source)", name: "Inspired CO2 from rebreathing (input)", unit: "mmHg", normal: "0", convention: "—" },
  { n: 132, s: '5.5', keys: ["resp.driver.source"], label: "Ventilation mode", name: "Spontaneous / BVM / ventilator / none", unit: "—", normal: "—", convention: "clinical words" },
  { n: 133, s: '5.5', keys: ["resp.driver.airway"], label: "Airway state", name: "Patent / obstructed / apnoea / disconnected / oesophageal / endobronchial / bronchospasm", unit: "—", normal: "—", convention: "clinical words" },
  { n: 134, s: '5.5', keys: ["ev.anaesthesia.drive.opioidDep", "ev.anaesthesia.drive.hypnoticDep", "ev.anaesthesia.drive.veRest", "ev.anaesthesia.drive.apnoea", "ev.anaesthesia.drive.obstruction"], label: "Respiratory drive (opioid / hypnotic depression, resting V̇E fraction, apnoea, upper-airway obstruction)", name: "Drug effect on ventilatory drive", unit: "fraction", normal: "0 / 1", convention: "engine (instructor)" },
  { n: 135, s: '5.5', keys: ["blood.lung.evlwi"], label: "EVLWI", name: "Extravascular lung water index", unit: "mL/kg", normal: "3–7 (oedema > 10)", convention: "PiCCO" },
  { n: 136, s: '5.5', keys: ["resp.lung.lp.ibwKg"], label: "PBW", name: "Predicted (ideal) body weight", unit: "kg", normal: "Devine", convention: "ARDSnet \"PBW\"" },
  { n: 137, s: '5.5', keys: [], label: "VTe", name: "Expired tidal volume (ventilator)", unit: "mL", normal: "6–8 mL/kg PBW", convention: "Ham \"VTE\"" },
  { n: 138, s: '5.5', keys: [], label: "MVe", name: "Expired minute volume", unit: "L/min", normal: "5–8", convention: "Ham \"ExpMinVol\"" },
  { n: 139, s: '5.5', keys: [], label: "fTotal", name: "Total breath rate (ventilator)", unit: "/min", normal: "12–20", convention: "Ham \"fTotal\"" },
  { n: 140, s: '5.5', keys: [], label: "P0.1", name: "Airway occlusion pressure at 100 ms", unit: "cmH₂O", normal: "1–4 (> 3.5 high drive)", convention: "Ham \"P0.1\"" },
  { n: 141, s: '5.5', keys: [], label: "RSBI", name: "Rapid shallow breathing index f/VT", unit: "breaths/min/L", normal: "< 105", convention: "Yang–Tobin" },
  { n: 142, s: '5.5', keys: [], label: "FiO₂ (set)", name: "Set O2 concentration", unit: "%", normal: "—", convention: "Ham \"Oxygen\"" },
  { n: 143, s: '5.6', keys: ["resp.mechanics.ppeak"], label: "Ppeak", name: "Peak inspiratory pressure", unit: "cmH₂O", normal: "< 30–35", convention: "Ham \"Ppeak\"; Dräger \"Ppeak\"/\"PIP\"" },
  { n: 144, s: '5.6', keys: ["resp.mechanics.pplat"], label: "Pplat", name: "Plateau pressure (end-inspiratory hold)", unit: "cmH₂O", normal: "< 30 (lung-protective ≤ 28–30)", convention: "ARDSnet; Ham \"Pplateau\"" },
  { n: 145, s: '5.6', keys: ["resp.driver.vent.peep"], label: "PEEP", name: "Set positive end-expiratory pressure", unit: "cmH₂O", normal: "5–15", convention: "all" },
  { n: 146, s: '5.6', keys: ["resp.mechanics.peepTot"], label: "PEEPtot", name: "Total PEEP (end-expiratory hold)", unit: "cmH₂O", normal: "= PEEP", convention: "Ham \"PEEPtot\"/\"Total PEEP\"" },
  { n: 147, s: '5.6', keys: ["resp.mechanics.peepi"], label: "PEEPi (auto-PEEP)", name: "Intrinsic PEEP = PEEPtot − PEEP", unit: "cmH₂O", normal: "0", convention: "Ham \"AutoPEEP\"; textbooks \"PEEPi\"" },
  { n: 148, s: '5.6', keys: ["resp.mechanics.dp"], label: "ΔP", name: "Driving pressure = Pplat − PEEPtot", unit: "cmH₂O", normal: "< 15 (≤ 13 target)", convention: "Amato 2015 \"ΔP\"/\"DP\"" },
  { n: 149, s: '5.6', keys: ["resp.mechanics.plEi", "resp.mechanics.plEe"], label: "PL (Pes-based, direct)", name: "Transpulmonary pressure = Paw − Ppl (Pes-based; end-insp and end-exp)", unit: "cmH₂O", normal: "awake spontaneous: end-exp ≈ +5, end-insp ≈ +8; supine ventilated: end-exp −5 to +2, end-insp < 20–25", other: "Preg/obese: Ppl higher", convention: "Talmor/Chiumello" },
  { n: 150, s: '5.6', keys: ["resp.mechanics.pesEi", "resp.mechanics.pesEe"], label: "Pes (estimate)", name: "Oesophageal pressure, an estimate (not a balloon measurement): awake, the pleural pressure; supine ventilated, 6.9 cmH₂O + 0.22 per BMI unit above 22.5 + the pleural-pressure change", unit: "cmH₂O", normal: "awake spontaneous: end-exp ≈ −5, end-insp ≈ −8; supine ventilated: end-exp ≈ 5–10", convention: "oesophageal manometry" },
  { n: 151, s: '5.6', keys: ["resp.mechanics.cstat"], label: "Cstat (Crs)", name: "Static respiratory-system compliance = VT/(Pplat − PEEPtot)", unit: "mL/cmH₂O", normal: "50–80 intubated (≈ 100 awake)", other: "child 1–1.5 mL/cmH₂O/kg / Preg ×0.85", convention: "Ham \"Cstat\"" },
  { n: 152, s: '5.6', keys: ["resp.mechanics.cdyn"], label: "Cdyn", name: "Dynamic compliance = VT/(Ppeak − PEEPtot)", unit: "mL/cmH₂O", normal: "40–70", convention: "textbooks" },
  { n: 153, s: '5.6', keys: ["resp.lung.lp.side.#.cL"], label: "CL", name: "Lung compliance (per side)", unit: "mL/cmH₂O", normal: "≈ 100–200 (both lungs, awake)", convention: "West" },
  { n: 154, s: '5.6', keys: ["ev.lungState.chestWallComplianceMlPerCmH2O", "resp.lung.lp.ccw"], label: "Ccw", name: "Chest-wall compliance", unit: "mL/cmH₂O", normal: "≈ 200", other: "Preg ×0.7", convention: "West" },
  { n: 155, s: '5.6', keys: ["resp.mechanics.rinsp"], label: "Raw (Rinsp / Rexp)", name: "Airway resistance incl. tube", unit: "cmH₂O·s/L", normal: "2–3 unintubated; 8–12 with ETT", other: "child higher", convention: "Ham \"Rinsp\"/\"Rexp\"; textbooks \"Raw\"" },
  { n: 156, s: '5.6', keys: ["resp.lung.lp.rTube"], label: "RETT", name: "Endotracheal-tube resistance", unit: "cmH₂O·s/L", normal: "4–8 (7.0–8.0 mm tube)", convention: "textbooks" },
  { n: 157, s: '5.6', keys: ["resp.lung.tauBar"], label: "RCexp (τE)", name: "Expiratory time constant", unit: "s", normal: "0.4–0.7 intubated", convention: "Ham \"RCexp\"" },
  { n: 158, s: '5.6', keys: ["resp.lung.mech.paw"], label: "Paw", name: "Airway pressure (instantaneous)", unit: "cmH₂O", normal: "—", convention: "all" },
  { n: 159, s: '5.6', keys: ["resp.lung.mech.pcar"], label: "Ptrach", name: "Tracheal (carinal) pressure", unit: "cmH₂O", normal: "—", convention: "textbooks" },
  { n: 160, s: '5.6', keys: [], label: "Pmean", name: "Mean airway pressure", unit: "cmH₂O", normal: "5–15", convention: "Ham \"Pmean\"" },
  { n: 161, s: '5.6', keys: ["resp.vd.anat"], label: "VD anat", name: "Anatomical dead space", unit: "mL (mL/kg PBW)", normal: "≈ 150 (2.2 mL/kg)", other: "child relatively larger with apparatus", convention: "Fowler" },
  { n: 162, s: '5.6', keys: ["resp.vd.app"], label: "VD app", name: "Apparatus dead space (HME, Y-piece, catheter mount)", unit: "mL", normal: "30–100", other: "child: large fraction of VT", convention: "textbooks" },
  { n: 163, s: '5.6', keys: ["resp.vd.alv"], label: "VD alv", name: "Alveolar dead space", unit: "mL", normal: "≈ 0 healthy", convention: "West" },
  { n: 164, s: '5.6', keys: ["resp.vd.phys"], label: "VD phys", name: "Physiological dead space (Bohr–Enghoff)", unit: "mL", normal: "≈ 150–200", convention: "West" },
  { n: 165, s: '5.6', keys: ["resp.vd.vdvt"], label: "VD/VT", name: "Enghoff dead-space fraction", unit: "%", normal: "20–35 % spontaneous; 30–45 % ventilated", convention: "Enghoff" },
  { n: 166, s: '5.6', keys: ["resp.volumes.frc"], label: "FRC", name: "Functional residual capacity", unit: "mL (mL/kg)", normal: "2.0–2.5 L supine (30 mL/kg); −20 % under GA", other: "child 30 mL/kg / Preg −20 %", convention: "ATS/ERS" },
  { n: 167, s: '5.6', keys: ["resp.volumes.rv"], label: "RV", name: "Residual volume", unit: "mL", normal: "≈ 1.2 L (16–20 mL/kg)", convention: "ATS/ERS" },
  { n: 168, s: '5.6', keys: ["resp.volumes.tlc"], label: "TLC", name: "Total lung capacity", unit: "mL", normal: "≈ 6 L (80 mL/kg)", convention: "ATS/ERS" },
  { n: 169, s: '5.6', keys: ["resp.volumes.erv"], label: "ERV", name: "Expiratory reserve volume = FRC − RV", unit: "mL", normal: "≈ 1.0–1.2 L", other: "Preg −20 %", convention: "ATS/ERS" },
  { n: 170, s: '5.6', keys: ["resp.volumes.ic"], label: "IC", name: "Inspiratory capacity = TLC − FRC", unit: "mL", normal: "≈ 3.5 L", other: "Preg ↑", convention: "ATS/ERS" },
  { n: 171, s: '5.6', keys: ["resp.volumes.vc"], label: "VC (SVC)", name: "Vital capacity = TLC − RV", unit: "mL", normal: "≈ 4.5–5 L (60–70 mL/kg)", convention: "ATS/ERS" },
  { n: 172, s: '5.6', keys: ["resp.volumes.fvc"], label: "FVC", name: "Forced vital capacity", unit: "mL", normal: "≥ 80 % predicted (≥ LLN)", convention: "ATS/ERS 2022" },
  { n: 173, s: '5.6', keys: ["resp.volumes.fev1"], label: "FEV₁", name: "Forced expiratory volume in 1 s", unit: "mL", normal: "≥ 80 % predicted", convention: "ATS/ERS" },
  { n: 174, s: '5.6', keys: ["resp.volumes.ratio"], label: "FEV₁/FVC", name: "Tiffeneau ratio", unit: "%", normal: "≥ 70 % (≥ LLN)", convention: "GOLD/ATS" },
  { n: 175, s: '5.6', keys: ["resp.volumes.pef"], label: "PEF", name: "Peak expiratory flow", unit: "L/min", normal: "400–600", convention: "ATS/ERS" },
  { n: 176, s: '5.6', keys: ["resp.volumes.cc"], label: "CC", name: "Closing capacity", unit: "mL", normal: "≈ FRC supine at 44 y, upright at 66 y", other: "Preg: CC > FRC supine", convention: "Nunn" },
  { n: 177, s: '5.6', keys: ["ev.lungState.atelectasisFrac", "resp.lung.rec.*.#"], label: "Atelectasis (%)", name: "Non-aerated lung fraction", unit: "%", normal: "0 awake; 5–10 after induction", other: "obese/Preg ↑", convention: "Hedenstierna" },
  { n: 178, s: '5.7', keys: ["ev.labs.values.ph", "ev.labResult.values.ph"], label: "pH", name: "Arterial (or venous) pH", unit: "—", normal: "7.35–7.45 (venous ≈ 0.03 lower)", other: "Preg 7.40–7.46", convention: "blood-gas analysers" },
  { n: 179, s: '5.7', keys: ["ev.labs.values.pco2", "ev.labResult.values.pco2"], label: "PaCO₂ / PvCO₂", name: "CO2 tension (a = arterial, v = venous)", unit: "mmHg (kPa option)", normal: "35–45", other: "Preg 28–32", convention: "analysers print \"pCO₂\" with the sample type" },
  { n: 180, s: '5.7', keys: ["ev.labs.values.po2", "ev.labResult.values.po2"], label: "PaO₂ / PvO₂", name: "O2 tension", unit: "mmHg", normal: "80–100 on air; venous 35–45", convention: "as 179" },
  { n: 181, s: '5.7', keys: ["ev.labs.values.hco3", "ev.labResult.values.hco3"], label: "HCO₃⁻", name: "Bicarbonate (actual; standard HCO₃ optional)", unit: "mmol/L", normal: "22–26", other: "Preg 18–22", convention: "analysers \"cHCO₃⁻(P)\"" },
  { n: 182, s: '5.7', keys: ["ev.labs.values.be", "ev.labResult.values.be"], label: "BE (SBE)", name: "Base excess (standard, extracellular)", unit: "mmol/L", normal: "−2 to +2", other: "Preg −2 to −4", convention: "analysers \"cBase(Ecf)\"" },
  { n: 183, s: '5.7', keys: ["ev.labs.values.so2", "ev.labResult.values.so2"], label: "FO₂Hb (or sO₂)", name: "Fractional oxyhaemoglobin (the engine value); show functional sO₂ separately", unit: "%", normal: "FO₂Hb 94–98; sO₂ 95–99", convention: "co-oximeters print both" },
  { n: 184, s: '5.7', keys: ["ev.labs.values.cohb", "ev.labResult.values.cohb"], label: "COHb", name: "Carboxyhaemoglobin", unit: "%", normal: "< 1.5 (smokers up to 10)", convention: "co-oximetry" },
  { n: 185, s: '5.7', keys: ["ev.labs.values.methb", "ev.labResult.values.methb"], label: "MetHb", name: "Methaemoglobin", unit: "%", normal: "< 1.5", convention: "co-oximetry" },
  { n: 186, s: '5.7', keys: ["ev.labs.values.lactate", "ev.labResult.values.lactate", "blood.out.lactate"], label: "Lactate", name: "Blood lactate", unit: "mmol/L", normal: "0.5–2.0", convention: "all" },
  { n: 187, s: '5.7', keys: ["ev.labs.values.na", "ev.labResult.values.na", "blood.out.na"], label: "Na⁺", name: "Sodium", unit: "mmol/L", normal: "135–145", other: "Preg 130–140", convention: "all" },
  { n: 188, s: '5.7', keys: ["ev.labs.values.k", "ev.labResult.values.k", "blood.out.k"], label: "K⁺", name: "Potassium", unit: "mmol/L", normal: "3.5–5.0", convention: "all" },
  { n: 189, s: '5.7', keys: ["ev.labs.values.cl", "ev.labResult.values.cl", "blood.out.cl"], label: "Cl⁻", name: "Chloride", unit: "mmol/L", normal: "98–107", convention: "all" },
  { n: 190, s: '5.7', keys: ["ev.labs.values.iCa", "ev.labResult.values.iCa", "blood.out.iCa"], label: "iCa²⁺", name: "Ionised calcium", unit: "mmol/L", normal: "1.15–1.30", convention: "analysers \"cCa²⁺\"" },
  { n: 191, s: '5.7', keys: ["ev.labs.values.mg", "ev.labResult.values.mg", "blood.out.mg"], label: "Mg²⁺", name: "Magnesium (total; ionised 0.45–0.6)", unit: "mmol/L", normal: "0.7–1.0 (MgSO4 therapeutic 2–3.5)", convention: "—" },
  { n: 192, s: '5.7', keys: ["ev.labs.values.hb", "ev.labResult.values.hb", "blood.out.hb"], label: "Hb", name: "Haemoglobin", unit: "g/dL (g/L option)", normal: "M 13.5–17.5; F 12–15.5", other: "child 11–13.5 / Preg ≥ 11 (T2 ≥ 10.5)", convention: "all" },
  { n: 193, s: '5.7', keys: ["ev.labs.values.glucose", "ev.labResult.values.glucose"], label: "Glucose", name: "Blood glucose", unit: "mmol/L and mg/dL", normal: "3.9–7.8 (70–140 mg/dL)", other: "neonate > 2.6", convention: "all" },
  { n: 194, s: '5.7', keys: ["ev.labs.values.ag", "ev.labResult.values.ag", "blood.out.ag"], label: "AG", name: "Anion gap (Na − Cl − HCO3)", unit: "mmol/L", normal: "8–12 (without K); correct for albumin", convention: "all" },
  { n: 195, s: '5.7', keys: ["ev.labs.values.osm", "ev.labResult.values.osm", "blood.out.osm"], label: "Osm", name: "Measured/calculated osmolality", unit: "mOsm/kg", normal: "275–295", other: "Preg ≈ 280", convention: "all" },
  { n: 196, s: '5.7', keys: [], label: "Hct", name: "Haematocrit", unit: "%", normal: "M 40–52; F 36–48", other: "Preg 32–36", convention: "all" },
  { n: 197, s: '5.7', keys: [], label: "WBC", name: "White-cell count", unit: "×10⁹/L", normal: "4–11", other: "Preg up to 15", convention: "CBC" },
  { n: 198, s: '5.7', keys: [], label: "Plt", name: "Platelet count", unit: "×10⁹/L", normal: "150–400", other: "Preg ≥ 100 (gestational thrombocytopenia)", convention: "CBC" },
  { n: 199, s: '5.7', keys: [], label: "Urea (BUN)", name: "Urea", unit: "mmol/L (mg/dL BUN)", normal: "2.5–7.8 (BUN 7–20)", other: "Preg ↓", convention: "chemistry" },
  { n: 200, s: '5.7', keys: [], label: "Creat", name: "Creatinine", unit: "µmol/L (mg/dL)", normal: "60–110 (0.6–1.2)", other: "Preg 35–70 (0.4–0.8)", convention: "chemistry; KDIGO" },
  { n: 201, s: '5.7', keys: ["blood.out.albuminGL"], label: "Alb", name: "Albumin", unit: "g/L", normal: "35–50", other: "Preg 28–37", convention: "chemistry" },
  { n: 202, s: '5.7', keys: ["blood.out.cop"], label: "COP", name: "Colloid osmotic (oncotic) pressure", unit: "mmHg", normal: "22–28", other: "Preg 21–22", convention: "textbooks" },
  { n: 203, s: '5.7', keys: ["blood.keto"], label: "BHB", name: "β-hydroxybutyrate (ketones)", unit: "mmol/L", normal: "< 0.6 (DKA > 3)", convention: "chemistry" },
  { n: 204, s: '5.7', keys: [], label: "cTn", name: "Cardiac troponin (hs)", unit: "ng/L", normal: "< 99th centile of the assay", convention: "chemistry" },
  { n: 205, s: '5.7', keys: [], label: "BNP / NT-proBNP", name: "Natriuretic peptide", unit: "pg/mL", normal: "BNP < 100; NT-proBNP < 125 (age-dependent)", convention: "chemistry" },
  { n: 206, s: '5.7', keys: [], label: "Bili", name: "Total bilirubin", unit: "µmol/L", normal: "5–21", convention: "LFT" },
  { n: 207, s: '5.7', keys: [], label: "ALT / AST", name: "Transaminases", unit: "U/L", normal: "ALT 7–56; AST 10–40", convention: "LFT" },
  { n: 208, s: '5.7', keys: [], label: "ALP / GGT", name: "Cholestatic enzymes", unit: "U/L", normal: "ALP 44–147; GGT 9–48", other: "Preg ALP ↑ (placental)", convention: "LFT" },
  { n: 209, s: '5.7', keys: [], label: "NH₃", name: "Ammonia", unit: "µmol/L", normal: "15–45", convention: "chemistry" },
  { n: 210, s: '5.7', keys: ["ev.organs.liver.inr"], label: "INR", name: "International normalised ratio (PT)", unit: "— (PT s)", normal: "0.8–1.2 (PT 11–13.5 s)", other: "Preg slightly ↓", convention: "coagulation" },
  { n: 211, s: '5.7', keys: [], label: "aPTT", name: "Activated partial thromboplastin time", unit: "s", normal: "25–35", other: "Preg ↓", convention: "coagulation" },
  { n: 212, s: '5.7', keys: [], label: "Fib", name: "Fibrinogen (Clauss)", unit: "g/L", normal: "2–4", other: "Preg 4–6 (< 2 in PPH predicts severity)", convention: "coagulation" },
  { n: 213, s: '5.7', keys: [], label: "ACT", name: "Activated clotting time", unit: "s", normal: "80–130 (CPB > 400–480)", convention: "point of care" },
  { n: 214, s: '5.7', keys: [], label: "D-dimer", name: "Fibrin degradation (D-dimer)", unit: "mg/L FEU", normal: "< 0.5", other: "Preg ↑ by trimester", convention: "coagulation" },
  { n: 215, s: '5.7', keys: [], label: "Anti-Xa", name: "Heparin anti-Xa activity", unit: "IU/mL", normal: "therapeutic UFH 0.3–0.7", convention: "coagulation" },
  { n: 216, s: '5.7', keys: [], label: "R", name: "TEG reaction time (to 2 mm)", unit: "min", normal: "5–10 (kaolin)", other: "Preg shorter", convention: "Haemonetics TEG" },
  { n: 217, s: '5.7', keys: [], label: "K", name: "TEG kinetics time (2 → 20 mm)", unit: "min", normal: "1–3", convention: "TEG" },
  { n: 218, s: '5.7', keys: [], label: "α", name: "TEG/ROTEM α-angle", unit: "°", normal: "53–72 (TEG kaolin)", other: "Preg ↑", convention: "TEG/ROTEM" },
  { n: 219, s: '5.7', keys: [], label: "MA", name: "TEG maximum amplitude", unit: "mm", normal: "50–70", other: "Preg ↑", convention: "TEG" },
  { n: 220, s: '5.7', keys: [], label: "LY30", name: "TEG lysis 30 min after MA", unit: "%", normal: "0–8", convention: "TEG" },
  { n: 221, s: '5.7', keys: [], label: "CT", name: "ROTEM clotting time (EXTEM / INTEM / FIBTEM / HEPTEM / APTEM)", unit: "s", normal: "EXTEM 38–79; INTEM 100–240", convention: "Werfen ROTEM" },
  { n: 222, s: '5.7', keys: [], label: "CFT", name: "ROTEM clot formation time", unit: "s", normal: "EXTEM 34–159", convention: "ROTEM" },
  { n: 223, s: '5.7', keys: [], label: "A10 (A5)", name: "ROTEM amplitude at 10 (5) min", unit: "mm", normal: "EXTEM 43–65; FIBTEM 7–23", other: "Preg FIBTEM ↑", convention: "ROTEM" },
  { n: 224, s: '5.7', keys: [], label: "MCF", name: "ROTEM maximum clot firmness", unit: "mm", normal: "EXTEM 50–72; FIBTEM 9–25", convention: "ROTEM" },
  { n: 225, s: '5.7', keys: [], label: "ML (LI30)", name: "ROTEM maximum lysis (lysis index at 30 min)", unit: "%", normal: "ML < 15", convention: "ROTEM" },
  { n: 226, s: '5.7', keys: ["ev.labResult.drawnAt", "ev.labs.drawnAt"], label: "Drawn / Reported", name: "Sample time and result time", unit: "clock", normal: "POC 1–2 min; lab 30–60 min", convention: "lab systems" },
  { n: 227, s: '5.8', keys: ["resp.temp.tc"], label: "Tcore", name: "Core temperature (truth)", unit: "°C", normal: "36.5–37.5", convention: "textbooks" },
  { n: 228, s: '5.8', keys: ["resp.temp.tp", "ev.endo.tempPeriphC"], label: "Tperiph", name: "Peripheral (skin/compartment) temperature", unit: "°C", normal: "30–35 (core–periph 2–4)", convention: "Phil \"Tperi\"" },
  { n: 229, s: '5.8', keys: ["resp.temp.ta"], label: "Troom", name: "Ambient temperature", unit: "°C", normal: "20–24 (theatre)", other: "neonate: thermoneutral 32–34", convention: "—" },
  { n: 230, s: '5.8', keys: ["resp.temp.sites.*"], label: "Toes, Tnaso, Ttymp, Tblad, Trect, Taxil", name: "Site temperatures", unit: "°C", normal: "axilla ≈ core − 0.5–1; rectal ≈ core + 0.2", convention: "Phil site labels" },
  { n: 231, s: '5.8', keys: ["ev.endo.shivering", "ev.endo.sweating", "ev.endo.vasoconstricted"], label: "Shivering / Sweating / Vasoconstricted", name: "Thermoregulatory responses", unit: "yes/no", normal: "thresholds shift under GA (Sessler)", convention: "clinical words" },
  { n: 232, s: '5.8', keys: ["endo.cascade.stage"], label: "Hypothermia stage", name: "Mild (32–35) / moderate (28–32) / severe (< 28)", unit: "—", normal: "—", convention: "ERC/Swiss staging" },
  { n: 233, s: '5.9', keys: ["ev.organs.brain.icp"], label: "ICP", name: "Intracranial pressure (truth)", unit: "mmHg", normal: "5–15", other: "infant 1.5–6", convention: "BTF" },
  { n: 234, s: '5.9', keys: ["ev.organs.brain.cpp"], label: "CPP", name: "Cerebral perfusion pressure (truth)", unit: "mmHg", normal: "60–80", convention: "BTF" },
  { n: 235, s: '5.9', keys: ["ev.organs.brain.mapHead"], label: "MAP (tragus)", name: "MAP referenced at the external auditory meatus", unit: "mmHg", normal: "MAP − 0.77·head-height (cm)", convention: "neuro-anaesthesia practice" },
  { n: 236, s: '5.9', keys: ["ev.organs.brain.cbf"], label: "CBF", name: "Cerebral blood flow", unit: "mL/100 g/min (engine × 50)", normal: "50 (40–60)", other: "child 70–100", convention: "textbooks" },
  { n: 237, s: '5.9', keys: ["ev.organs.brain.cbvMl"], label: "CBV", name: "Cerebral blood volume", unit: "mL", normal: "≈ 50 (3–4 mL/100 g)", convention: "textbooks" },
  { n: 238, s: '5.9', keys: ["ev.organs.brain.cmro2"], label: "CMRO₂", name: "Cerebral metabolic rate for O2", unit: "mL/100 g/min (engine relative)", normal: "3.0–3.5", other: "child ≈ 5", convention: "textbooks" },
  { n: 239, s: '5.9', keys: ["ev.organs.brain.sjvo2"], label: "SjvO₂", name: "Jugular bulb venous O2 saturation", unit: "% (engine fraction)", normal: "55–75", convention: "neurocritical care" },
  { n: 240, s: '5.9', keys: ["ev.organs.brain.elastance"], label: "Intracranial elastance", name: "ΔP/ΔV (inverse compliance)", unit: "mmHg/mL", normal: "low at normal ICP (PVI ≈ 25 mL)", convention: "Marmarou" },
  { n: 241, s: '5.9', keys: ["ev.organs.brain.state"], label: "ICP state", name: "Normal / raised ICP / Cushing response / herniation", unit: "—", normal: "—", convention: "clinical words" },
  { n: 242, s: '5.9', keys: ["organs.brain.headUpDeg"], label: "Head-up (HOB)", name: "Head-of-bed elevation", unit: "°", normal: "30 in TBI", convention: "nursing/ICU" },
  { n: 243, s: '5.9', keys: ["organs.brain.mass", "organs.brain.oedema"], label: "Haematoma / oedema volume", name: "Intracranial mass volume", unit: "mL", normal: "0", convention: "radiology" },
  { n: 244, s: '5.9', keys: ["ev.anaesthesia.outputs.pupilMm"], label: "Pupils", name: "Pupil diameter (add reactivity, symmetry)", unit: "mm", normal: "2–4 (light)", convention: "GCS/neuro obs" },
  { n: 245, s: '5.10', keys: ["ev.organs.kidney.uopMlKgH", "ev.organs.kidney.uop1hMlKgH"], label: "UO", name: "Urine output (instant, last hour)", unit: "mL/kg/h", normal: "≥ 0.5", other: "child ≥ 1", convention: "KDIGO" },
  { n: 246, s: '5.10', keys: ["ev.organs.kidney.cumMl", "ev.organs.kidney.bagMl"], label: "UO total / Urometer", name: "Cumulative urine; bag volume", unit: "mL", normal: "—", convention: "fluid chart" },
  { n: 247, s: '5.10', keys: ["ev.organs.kidney.rbf"], label: "RBF", name: "Renal blood flow (engine 552 mL/min at rest under GA: check the definition against the normal)", unit: "mL/min", normal: "1,000–1,200 (≈ 20 % of CO)", other: "Preg +50 %", convention: "textbooks" },
  { n: 248, s: '5.10', keys: ["ev.organs.kidney.gfr"], label: "GFR", name: "Glomerular filtration rate", unit: "mL/min (mL/min/1.73 m²)", normal: "90–120", other: "Preg +50 %", convention: "KDIGO" },
  { n: 249, s: '5.10', keys: ["ev.organs.kidney.akiStage"], label: "AKI stage (KDIGO)", name: "KDIGO stage 0–3 (UO criterion only until creatinine exists)", unit: "0–3", normal: "0", convention: "KDIGO" },
  { n: 250, s: '5.10', keys: ["ev.organs.kidney.oliguria"], label: "Oliguria", name: "UO < 0.5 mL/kg/h (≥ 6 h for KDIGO)", unit: "yes/no", normal: "no", other: "child < 1", convention: "KDIGO" },
  { n: 251, s: '5.10', keys: ["ev.organs.kidney.bladderMl"], label: "Bladder volume", name: "Bladder urine volume (no catheter)", unit: "mL", normal: "< 400–500", convention: "bladder scan" },
  { n: 252, s: '5.10', keys: ["organs.iap"], label: "IAP", name: "Intra-abdominal pressure", unit: "mmHg", normal: "0–5 (IAH ≥ 12; ACS > 20 + organ failure)", other: "Preg ↑", convention: "WSACS" },
  { n: 253, s: '5.11', keys: ["ev.organs.liver.hbfRel"], label: "HBF", name: "Hepatic blood flow (engine relative)", unit: "L/min (× baseline)", normal: "≈ 1.5 (25 % of CO)", convention: "textbooks" },
  { n: 254, s: '5.11', keys: ["ev.organs.liver.kLacPerH"], label: "Lactate clearance", name: "Hepatic lactate clearance constant", unit: "/h (show t½)", normal: "t½ ≈ 20–30 min", convention: "textbooks (clearance %)" },
  { n: 255, s: '5.11', keys: ["ev.organs.liver.liverFn"], label: "Liver function", name: "Liver synthetic/metabolic function index (model)", unit: "0–1", normal: "1", convention: "engine; label as MELD/Child–Pugh-like only when the labs exist" },
  { n: 256, s: '5.11', keys: ["ev.endo.glucoseMmolL", "ev.endo.glucoseMgDl"], label: "Glucose", name: "Blood glucose (truth)", unit: "mmol/L (mg/dL)", normal: "3.9–7.8", convention: "all" },
  { n: 257, s: '5.11', keys: ["ev.endo.insulinUuMl"], label: "Insulin", name: "Plasma insulin", unit: "µU/mL (mU/L)", normal: "fasting 2–20", other: "Preg ↑ (insulin resistance)", convention: "chemistry" },
  { n: 258, s: '5.11', keys: ["ev.endo.epinephrinePgMl"], label: "Adrenaline", name: "Plasma adrenaline", unit: "pg/mL", normal: "< 50–100 at rest", convention: "chemistry" },
  { n: 259, s: '5.11', keys: ["ev.endo.norepinephrinePgMl"], label: "Noradrenaline", name: "Plasma noradrenaline", unit: "pg/mL", normal: "100–400 at rest", convention: "chemistry" },
  { n: 260, s: '5.11', keys: ["ev.endo.cortisolNmolL"], label: "Cortisol", name: "Plasma cortisol", unit: "nmol/L", normal: "140–690 (morning)", other: "Preg ↑", convention: "chemistry" },
  { n: 261, s: '5.11', keys: ["ev.endo.stressIndex"], label: "Stress response", name: "Surgical stress index (model; instructor)", unit: "0–1", normal: "0", convention: "engine" },
  { n: 262, s: '5.11', keys: ["ev.endo.mhActivity"], label: "MH activity", name: "Malignant hyperthermia crisis activity (instructor)", unit: "0–1", normal: "0", convention: "engine" },
  { n: 263, s: '5.12', keys: ["ev.anaesthesia.tof.t1"], label: "T1", name: "First-twitch height (% control)", unit: "%", normal: "100", convention: "NMT monitors" },
  { n: 264, s: '5.12', keys: ["ev.anaesthesia.block.thumb", "ev.anaesthesia.block.dia"], label: "Block (AP / diaphragm)", name: "Fractional receptor block at adductor pollicis and diaphragm", unit: "%", normal: "0", convention: "teaching" },
  { n: 265, s: '5.12', keys: ["ev.anaesthesia.macBrain", "ev.anaesthesia.macEff"], label: "MAC (brain), MAC (opioid-adjusted)", name: "Brain partial-pressure MAC; effective MAC after opioid reduction", unit: "MAC", normal: "—", convention: "teaching" },
  { n: 266, s: '5.12', keys: ["ev.anaesthesia.etPct.<agent>"], label: "EtSEV / EtISO / EtDES / EtN₂O", name: "End-tidal agent per agent", unit: "%", normal: "—", convention: "Phil/GE agent labels" },
  { n: 267, s: '5.12', keys: ["ev.anaesthesia.conscious", "ev.anaesthesia.awarenessRisk", "ev.anaesthesia.movement"], label: "Consciousness / Awareness risk / Movement", name: "Clinical state flags", unit: "yes/no", normal: "—", convention: "clinical words" },
  { n: 268, s: '5.12', keys: ["ev.anaesthesia.outputs.antinoc"], label: "Antinociception", name: "Opioid/hypnotic antinociception level (model; the analgesia monitors NOL/ANI/SPI are its clinical cousins)", unit: "0–1", normal: "—", convention: "engine" },
  { n: 269, s: '5.12', keys: ["ev.neuroMark.kind"], label: "Event", name: "Fasciculation, movement, awareness, emergence, loss of consciousness, apnoea, breathing, recurarisation, MH trigger", unit: "—", normal: "—", convention: "clinical words" },
  { n: 270, s: '5.13', keys: ["ev.drugs.drugs.<id>.cp"], label: "Cp", name: "Plasma concentration", unit: "drug unit (µg/mL propofol; ng/mL opioids, NMBs)", normal: "", convention: "TCI pumps \"Cp\"" },
  { n: 271, s: '5.13', keys: ["ev.drugs.drugs.<id>.ce"], label: "Ce", name: "Effect-site concentration", unit: "drug unit", normal: "", convention: "TCI pumps \"Ce\"" },
  { n: 272, s: '5.13', keys: ["ev.drugs.drugs.<id>.rate", "ev.drugs.drugs.<id>.tci"], label: "Rate / Target", name: "Infusion rate; TCI target (plasma or effect, model name)", unit: "per row", normal: "", convention: "TCI pumps" },
  { n: 273, s: '5.13', keys: ["ev.drugs.drugs.<id>.totalAmount"], label: "Total", name: "Cumulative dose", unit: "mg, µg", normal: "", convention: "anaesthesia record" },
  { n: 274, s: '5.13', keys: ["ev.drugs.drugs.<id>.decrement50Min"], label: "CSHT (50 %)", name: "Context-sensitive half-time (time for Cp to fall 50 % if stopped now)", unit: "min", normal: "", convention: "Hughes 1992 \"CSHT\"" },
  { n: 275, s: '5.13', keys: ["ev.drugs.volatile.fi", "ev.drugs.volatile.fa"], label: "Fi / Fet (agent)", name: "Inspired and end-tidal (alveolar) agent fraction", unit: "%", normal: "", convention: "agent monitor \"Fi/Et\"" },
  { n: 276, s: '5.13', keys: ["ev.drugs.volatile.dialPct", "ev.drugs.volatile.fgfLpm"], label: "Dial / FGF", name: "Vaporiser setting; fresh gas flow", unit: "%, L/min", normal: "", convention: "anaesthesia machine" },
  { n: 277, s: '5.13', keys: ["ev.drugs.volatile.macAge"], label: "MAC (age)", name: "Age-adjusted 1 MAC of the agent", unit: "%", normal: "", convention: "Mapleson 1996" },
  { n: 278, s: '5.13', keys: ["pk.bus.agents.<id>.nmj", "pk.bus.agents.<id>.dia", "pk.bus.agents.<id>.vent"], label: "Ce (NMJ / diaphragm / ventilatory)", name: "Site-specific effect-site concentrations", unit: "drug unit", normal: "", convention: "teaching" },
  { n: 279, s: '5.13', keys: ["pk.bus.cns.*", "pk.bus.airway.*", "pk.bus.airway.hpvInhibit", "hemo.circ.ext.avNodeBlock"], label: "Drug effects (CNS, bronchodilation, histamine, HPV inhibition, AV-node block)", name: "Class-level effects (instructor)", unit: "fraction", normal: "", convention: "engine" },
  { n: 280, s: '5.14', keys: ["dev.defib.energyJ", "dev.defib.state", "dev.defib.sync", "dev.defib.shocks"], label: "Energy / Charging–Ready / SYNC / Shocks", name: "Defibrillator", unit: "J", normal: "biphasic adult 120–200; child 2–4 J/kg", convention: "defibrillators" },
  { n: 281, s: '5.14', keys: ["dev.pacer.mode", "dev.pacer.ratePpm", "dev.pacer.mA"], label: "Pacer mode / Rate / Output", name: "Transcutaneous pacer", unit: "ppm, mA", normal: "rate 60–80; capture typically 40–80 mA", convention: "defibrillators (\"PACER … ppm … mA\")" },
  { n: 282, s: '5.14', keys: ["ev.state.values.paceThresholdMa"], label: "Capture threshold", name: "Current needed for electrical capture", unit: "mA", normal: "40–80", convention: "—" },
  { n: 283, s: '5.14', keys: ["hemo.cpr.rate", "hemo.cpr.quality"], label: "CPR rate / quality", name: "Compression rate; depth/recoil quality (model 0–1.2)", unit: "/min, —", normal: "100–120/min, depth 5–6 cm, CCF > 60 %", convention: "ERC/AHA" },
  { n: 284, s: '5.14', keys: ["hemo.iabp.ratio", "hemo.iabp.volumeMl", "hemo.iabp.inflateOffsetMs", "hemo.iabp.deflateOffsetMs"], label: "IABP ratio / Balloon volume / Timing", name: "Intra-aortic balloon pump", unit: "1:1–1:3, mL, ms", normal: "40 mL balloon", convention: "IABP consoles" },
  { n: 285, s: '5.14', keys: ["ev.circ.lvad.flowLpm", "ev.circ.lvad.pi", "ev.circ.lvad.powerW", "ev.circ.lvad.suction"], label: "Speed / Flow / PI (LVAD) / Power / Suction", name: "Continuous-flow LVAD", unit: "rpm, L/min, —, W", normal: "HM3 speed 5,000–6,000; flow 4–6; power 4–5 W", convention: "LVAD controllers" },
  { n: 286, s: '5.14', keys: ["resp.driver.preox"], label: "Preoxygenation", name: "Face-mask preoxygenation (FiO2, duration)", unit: "—, s", normal: "3 min tidal or 8 deep breaths", convention: "Miller" },
  { n: 287, s: '5.15', keys: ["profile.pregnancyWeeks"], label: "GA (weeks)", name: "Gestational age", unit: "weeks", normal: "37–42 term", convention: "obstetrics" },
  { n: 288, s: '5.15', keys: [], label: "FHR", name: "Fetal heart rate baseline", unit: "bpm", normal: "110–160", convention: "NICE/FIGO CTG" },
  { n: 289, s: '5.15', keys: [], label: "Variability", name: "Baseline variability", unit: "bpm", normal: "5–25", convention: "FIGO" },
  { n: 290, s: '5.15', keys: [], label: "Decels (early / late / variable / prolonged)", name: "FHR decelerations", unit: "—", normal: "none or early", convention: "FIGO" },
  { n: 291, s: '5.15', keys: [], label: "Toco (UA)", name: "Uterine activity / contractions", unit: "mmHg or a.u.; /10 min", normal: "≤ 5 per 10 min", convention: "CTG" },
  { n: 292, s: '5.15', keys: [], label: "UBF", name: "Uterine blood flow", unit: "mL/min", normal: "≈ 700–800 at term (≈ 10 % of CO)", convention: "obstetric physiology" },
  { n: 293, s: '5.15', keys: [], label: "Tilt / position", name: "Left lateral tilt; supine hypotension", unit: "°", normal: "≥ 15° left tilt", convention: "obstetric anaesthesia" },
  { n: 294, s: '5.15', keys: [], label: "Block height", name: "Sensory block level (dermatome)", unit: "T-level", normal: "T4 for caesarean", convention: "obstetric anaesthesia" },
];

/**
 * Stage 9 additions (Ali reviews them with the glossary, R56): labels the instructor controls need that research/11 does
 * not list as a monitored quantity. Numbers 295–299 are these five; entries added at Task 0/2 (the labels of the truth
 * leaves FU-4, V.1, FU-6, FU-7 and 7k add) start at 300. research/11's numbers 1–294 never change.
 */
export const GLOSSARY_S9: readonly GlossaryEntry[] = [
  { n: 295, s: 'S9', keys: [], label: 'BP', name: 'Arterial blood pressure target (systolic / diastolic): what ART and NIBP read', unit: 'mmHg', normal: '90–140 / 60–90' },
  { n: 296, s: 'S9', keys: [], label: 'Rhythm', name: 'ECG rhythm', unit: '', normal: 'Sinus' },
  { n: 297, s: 'S9', keys: [], label: 'Onset', name: 'Time over which a change reaches its target', unit: 's', normal: '' },
  { n: 298, s: 'S9', keys: ['ev.state.values.contractility'], label: 'Contractility (×)', name: 'Instructor input in MANUAL mode: contractility as a multiple of the patient\'s baseline', unit: '× baseline', normal: '1' },
  { n: 299, s: 'S9', keys: ['ev.state.values.volumeStatus'], label: 'Volume status (×)', name: 'Instructor input in MANUAL mode: 1 = normal circulating volume, 0 = severe hypovolaemia', unit: '× baseline', normal: '1' },
  // Task 0/2 (R-S9-7): truth leaves V.1 and FU-6 added, with the labels their plans proposed (for Ali's review)
  { n: 300, s: 'S9', keys: ['resp.lung.lp.waterShunt'], label: 'Lung-water shunt', name: 'Lung-water shunt (PEEP-responsive part of the extra shunt)', unit: 'fraction', normal: '0' },
  { n: 301, s: 'S9', keys: ['ev.lungState.pleuralCmH2O'], label: 'Ppl (extra)', name: 'Pleural pressure from an effusion, haemothorax or pneumothorax', unit: 'cmH₂O', normal: '0' },
  { n: 302, s: 'S9', keys: ['neuro.resp.loc'], label: 'LOC', name: 'Loss of consciousness (its effect on the ventilatory drive)', unit: '0–1', normal: '0' },
  { n: 303, s: 'S9', keys: ['neuro.resp.pain'], label: 'Nociceptive drive', name: 'Nociceptive (pain) drive to breathe', unit: '0–1', normal: '0' },
  { n: 304, s: 'S9', keys: ['neuro.resp.hvrDep'], label: 'HVR depression', name: 'Hypoxic ventilatory response depression', unit: '0–1', normal: '0' },
  // Stage 7k's new truth leaves (its plan's N1–N7, numbered after 304; for Ali's review)
  { n: 305, s: 'S9', keys: ['resp.volumes.frcSit'], label: 'FRC (seated, PFT)', name: 'Functional residual capacity, seated (pulmonary function test)', unit: 'mL', normal: 'ECSC predicted' },
  { n: 306, s: 'S9', keys: ['resp.vd.peco2'], label: 'PĒCO₂', name: 'Mixed-expired CO₂ tension', unit: 'mmHg', normal: '≈ 25–30' },
  { n: 307, s: 'S9', keys: ['resp.mechanics.elErs'], label: 'EL/Ers', name: 'Lung share of respiratory-system elastance', unit: 'ratio', normal: '≈ 0.5–0.8' },
  { n: 308, s: 'S9', keys: ['resp.mechanics.flow'], label: 'V̇insp', name: 'Mean inspiratory flow', unit: 'L/s', normal: '—' },
  { n: 309, s: 'S9', keys: ['resp.volumes.fet'], label: 'FET', name: 'Forced expiratory time', unit: 's', normal: '< 6' },
  { n: 310, s: 'S9', keys: ['resp.volumes.pattern'], label: 'Spirometry pattern', name: 'Spirometry pattern (normal, obstructive, restrictive or mixed)', unit: '', normal: 'normal' },
  { n: 311, s: 'S9', keys: ['resp.volumes.pred.tlc', 'resp.volumes.pred.rv', 'resp.volumes.pred.frc', 'resp.volumes.pred.vc', 'resp.volumes.pred.fvc', 'resp.volumes.pred.fev1', 'resp.volumes.pred.ratio', 'resp.volumes.pred.pef'], label: 'Predicted', name: 'Predicted value (ECSC 1993 adults, Zapletal children)', unit: '', normal: '—' },
  { n: 312, s: 'S9', keys: ['resp.lung.lp.side.#.vdAlv'], label: 'VD alv fraction', name: 'Alveolar dead space as a fraction of alveolar ventilation, per lung', unit: 'fraction', normal: '≈ 0 healthy' },
  // FU-9's new truth leaves (blood, fluids, acid–base and kidney integration; numbered after 312, for Ali's review)
  { n: 313, s: 'S9', keys: ['blood.core.fl.globG'], label: 'Globulins (plasma)', name: 'Plasma globulin mass: with albumin it sets the colloid osmotic pressure', unit: 'g', normal: '≈ 65 at 70 kg (24 g/L)' },
  { n: 314, s: 'S9', keys: ['blood.core.hbfFactor'], label: 'HBF factor', name: 'Hepatic blood-flow factor: splanchnic constriction, volatile agent and hepatic outflow pressure (CVP or intra-abdominal pressure)', unit: '× baseline', normal: '1' },
  { n: 315, s: 'S9', keys: ['blood.core.renal.excretion.mannitol'], label: 'Mannitol excretion', name: 'Renal mannitol excretion', unit: 'mmol/h', normal: '0' },
  { n: 316, s: 'S9', keys: ['blood.core.so.mannitol'], label: 'Mannitol (ECF)', name: 'Mannitol in the extracellular fluid: effective osmoles (1 mmol = 1 mOsm)', unit: 'mmol', normal: '0' },
  { n: 317, s: 'S9', keys: ['blood.core.so.set.kIcf'], label: 'K⁺ cell store (reference)', name: 'Resting intracellular potassium store: the reference for total-body potassium balance', unit: 'mmol', normal: '≈ 3 900 at 70 kg' },
  { n: 318, s: 'S9', keys: ['organs.brain.osm0'], label: 'Osm (brain reference)', name: 'Resting plasma osmolality the brain is adapted to', unit: 'mOsm/kg', normal: '275–295' },
  { n: 319, s: 'S9', keys: ['organs.brain.osmWater'], label: 'Brain water (hypo-osmolar)', name: 'Brain water gained from a fall in plasma osmolality (hyponatraemic swelling)', unit: 'mL', normal: '0' },
  { n: 320, s: 'S9', keys: ['organs.renal.eabvLp'], label: 'EABV', name: 'Effective arterial blood volume sensed by the kidney: blood volume, or cardiac output against oxygen demand', unit: '× normal', normal: '1' },
  { n: 321, s: 'S9', keys: ['organs.view.demandRel'], label: 'O₂ demand (×)', name: 'Whole-body oxygen demand relative to rest: anaesthesia, temperature, fever', unit: '× rest', normal: '1 awake; ≈ 0.85 under GA' },
  { n: 322, s: 'S9', keys: ['organs.view.mannitolMmol'], label: 'Mannitol (kidney input)', name: 'Plasma mannitol as the kidney reads it (osmotic diuresis)', unit: 'mmol', normal: '0' },
  { n: 323, s: 'S9', keys: ['organs.view.osm'], label: 'Osm (organ input)', name: 'Plasma osmolality as the brain and kidney read it', unit: 'mOsm/kg', normal: '275–295' },
  // FU-10's new truth leaves (endocrine and thermal integration, Part A; numbered after 323, for Ali's review)
  { n: 324, s: 'S9', keys: ['resp.temp.ageY'], label: 'Age (thermoregulation)', name: 'Patient age as the thermoregulatory thresholds read it: the cold-defence thresholds fall with age under anaesthesia', unit: 'years', normal: '—' },
  { n: 325, s: 'S9', keys: ['endo.ageY'], label: 'Age (endocrine)', name: 'Patient age as the endocrine model holds it', unit: 'years', normal: '—' },
  { n: 326, s: 'S9', keys: ['endo.core.etomSuppr'], label: 'Etomidate adrenal suppression', name: 'Adrenal 11β-hydroxylase suppression left by etomidate: blunts the cortisol response, recovers over hours', unit: '0–1', normal: '0' },
  { n: 327, s: 'S9', keys: ['endo.core.ketoDef'], label: 'Ketogenic insulin deficit', name: 'Insulin deficit that drives ketone production and moves potassium out of the cells', unit: '0–1', normal: '0' },
  { n: 328, s: 'S9', keys: ['blood.core.endoKetoMmolMin'], label: 'Ketone production', name: 'Ketoacid production from insulin deficiency, into the ketoacid pool', unit: 'mmol/min', normal: '0' },
  { n: 329, s: 'S9', keys: ['blood.core.endoKetoUtilPerMin'], label: 'Ketone utilisation', name: 'Insulin-dependent ketone utilisation: fraction of the ketoacid pool cleared per minute', unit: '/min', normal: '≈ 0.0004 at basal insulin' },
  { n: 330, s: 'S9', keys: ['neuro.mhExposure.sux'], label: 'MH trigger: succinylcholine', name: 'When an MH-susceptible patient was first given succinylcholine', unit: 's', normal: 'never' },
  { n: 331, s: 'S9', keys: ['neuro.mhExposure.volatile', 'neuro.mhExposure.volatileAgent'], label: 'MH trigger: volatile', name: 'When an MH-susceptible patient was first exposed to a volatile agent, and which agent', unit: 's', normal: 'never' },
  { n: 332, s: 'S9', keys: ['endo.mhOwner'], label: 'MH source', name: 'Whether the malignant hyperthermia came from its triggers or from the instructor', unit: '', normal: '—' },
];

/**
 * Stage 9: the per-key label where one research/11 entry names several quantities ("NIBP S/D/M", "Dial / FGF"): each
 * truth path gets its own part (research/11 §5.16 rule 3: collisions resolved by the label). Reviewed with the glossary.
 */
export const KEY_LABELS: Readonly<Record<string, string>> = {
  // Stage 7k (its plan's Requests → Stage 9): one label per truth path where an entry names two readings
  'resp.mechanics.plEi': 'PL,ei', 'resp.mechanics.plEe': 'PL,ee', 'resp.mechanics.pesEi': 'Pes,ei (est.)', 'resp.mechanics.pesEe': 'Pes,ee (est.)',
  'resp.mechanics.rinsp': 'Rinsp',
  // FU-10: entry 331 names two readings
  'neuro.mhExposure.volatile': 'MH trigger: volatile (time)', 'neuro.mhExposure.volatileAgent': 'MH trigger: volatile (agent)',
  'resp.volumes.pred.tlc': 'TLC predicted', 'resp.volumes.pred.rv': 'RV predicted', 'resp.volumes.pred.frc': 'FRC (seated) predicted', 'resp.volumes.pred.vc': 'VC predicted',
  'resp.volumes.pred.fvc': 'FVC predicted', 'resp.volumes.pred.fev1': 'FEV₁ predicted', 'resp.volumes.pred.ratio': 'FEV₁/FVC predicted', 'resp.volumes.pred.pef': 'PEF predicted',
  'mon.nibpSys': 'NIBP S', 'mon.nibpDia': 'NIBP D', 'mon.nibpMean': 'NIBP M',
  'ev.breath.tiS': 'Ti', 'ev.breath.teS': 'Te',
  'resp.driver.vent.rr': 'f set', 'resp.driver.vent.vt': 'VT set', 'resp.driver.vent.peep': 'PEEP', 'resp.driver.vent.ie': 'I:E',
  'ev.labs.values.pco2': 'PCO₂', 'ev.labResult.values.pco2': 'PCO₂', 'ev.labs.values.po2': 'PO₂', 'ev.labResult.values.po2': 'PO₂',
  'ev.labResult.drawnAt': 'Reported', 'ev.labs.drawnAt': 'Drawn',
  'ev.endo.shivering': 'Shivering', 'ev.endo.sweating': 'Sweating', 'ev.endo.vasoconstricted': 'Vasoconstricted',
  'organs.brain.mass': 'Haematoma volume', 'organs.brain.oedema': 'Oedema volume',
  'ev.organs.kidney.cumMl': 'UO total', 'ev.organs.kidney.bagMl': 'Urometer',
  'ev.anaesthesia.macBrain': 'MAC (brain)', 'ev.anaesthesia.macEff': 'MAC (opioid-adjusted)',
  'ev.anaesthesia.conscious': 'Consciousness', 'ev.anaesthesia.awarenessRisk': 'Awareness risk', 'ev.anaesthesia.movement': 'Movement',
  'ev.drugs.volatile.fi': 'Fi (agent)', 'ev.drugs.volatile.fa': 'Fet (agent)', 'ev.drugs.volatile.dialPct': 'Dial', 'ev.drugs.volatile.fgfLpm': 'FGF',
  'dev.defib.energyJ': 'Energy', 'dev.defib.state': 'Charging–ready', 'dev.defib.sync': 'SYNC', 'dev.defib.shocks': 'Shocks',
  'dev.pacer.mode': 'Pacer mode', 'dev.pacer.ratePpm': 'Pacer rate', 'dev.pacer.mA': 'Pacer output',
  'hemo.cpr.rate': 'CPR rate', 'hemo.cpr.quality': 'CPR quality',
  'hemo.iabp.ratio': 'IABP ratio', 'hemo.iabp.volumeMl': 'Balloon volume', 'hemo.iabp.inflateOffsetMs': 'Inflation timing', 'hemo.iabp.deflateOffsetMs': 'Deflation timing',
  'ev.circ.lvad.flowLpm': 'LVAD flow', 'ev.circ.lvad.pi': 'PI (LVAD)', 'ev.circ.lvad.powerW': 'LVAD power', 'ev.circ.lvad.suction': 'Suction',
  'hemo.circ.p.eesLv': 'Ees LV', 'hemo.circ.p.eesRv': 'Ees RV', 'hemo.circ.p.v0Sv': 'Vu', 'hemo.circ.p.cSv': 'Cv',
  'hemo.circOut.qLungL': 'Q̇ L lung', 'hemo.circOut.qLungR': 'Q̇ R lung', 'hemo.circ.baro.es': 'Sympathetic tone', 'hemo.circ.baro.ev': 'Vagal tone',
  'ev.state.values.contractility': 'Contractility (×)', 'ev.state.values.volumeStatus': 'Volume status (×)',
  // pattern keys (the key string as written in `keys`): one entry, several quantities per drug or site
  'ev.drugs.drugs.<id>.rate': 'Infusion rate', 'ev.drugs.drugs.<id>.tci': 'TCI target',
  'pk.bus.agents.<id>.nmj': 'Ce NMJ', 'pk.bus.agents.<id>.dia': 'Ce diaphragm', 'pk.bus.agents.<id>.vent': 'Ce ventilatory',
  // a '*' key names several quantities under one label: only the paths named here get a clinical label (review F1)
  'resp.temp.sites.oesophageal': 'Toes', 'resp.temp.sites.nasopharyngeal': 'Tnaso', 'resp.temp.sites.tympanic': 'Ttymp',
  'resp.temp.sites.bladder': 'Tblad', 'resp.temp.sites.rectal': 'Trect', 'resp.temp.sites.axilla': 'Taxil',
};

/**
 * Stage 9 (review F1): the screen label where research/11's label, shortened, would name two different quantities.
 * "T1" is both the core temperature (19) and the first twitch of the train-of-four (263); "UO" is mL/h (34) and
 * mL/kg/h (245). Reviewed by Ali with the glossary.
 */
export const SHORT: Readonly<Record<number, string>> = { 245: 'UO/kg', 263: 'TOF T1' };

/**
 * Stage 9 (review F1): entries that are the same quantity as another entry (the truth copy of a monitor value), so a
 * screen may show them under one label and Explore shows one row. Every other pair of entries must differ in label.
 */
export const SAME_AS: Readonly<Record<number, number>> = { 233: 31, 234: 32, 256: 193 };

/**
 * Drug display names (orchestrator ruling 5 on the R50 review: drug names join the glossary, R56). One row per drug of
 * the 7g library (placeholders without PD excluded), generated once from its `DRUGS` names and edited by hand from now
 * on. `uk` is the name the site's "adrenaline / noradrenaline" set shows; the set is a site-profile option, default
 * "epinephrine / norepinephrine" (Ali's open question Q13). A drug a later stage adds shows its library name until it
 * gets a row here.
 */
export const DRUG_NAMES: Readonly<Record<string, { name: string; uk?: string }>> = {
  adenosine: { name: "Adenosine" }, amiodarone: { name: "Amiodarone" }, atropine: { name: "Atropine" },
  bupivacaine: { name: "Bupivacaine" }, calciumChloride: { name: "Calcium chloride 10 %" }, calciumGluconate: { name: "Calcium gluconate 10 %" },
  cisatracurium: { name: "Cisatracurium" }, dantrolene: { name: "Dantrolene" }, desflurane: { name: "Desflurane" },
  dexmedetomidine: { name: "Dexmedetomidine" }, dextrose: { name: "Dextrose 50 %" }, dobutamine: { name: "Dobutamine" },
  dopamine: { name: "Dopamine" }, ephedrine: { name: "Ephedrine" }, epinephrine: { name: "Epinephrine", uk: "Adrenaline" },
  esmolol: { name: "Esmolol" }, etomidate: { name: "Etomidate" }, fentanyl: { name: "Fentanyl" },
  flumazenil: { name: "Flumazenil" }, furosemide: { name: "Furosemide" }, glycopyrrolate: { name: "Glycopyrrolate" },
  hydralazine: { name: "Hydralazine" }, hypertonicSaline: { name: "Hypertonic saline 3 %/7.5 %/23.4 %" }, insulin: { name: "Insulin (regular)" },
  insulinDextrose: { name: "Insulin + dextrose" }, isoflurane: { name: "Isoflurane" }, ketamine: { name: "Ketamine" },
  labetalol: { name: "Labetalol" }, lidocaine: { name: "Lidocaine" }, lipidEmulsion: { name: "Lipid emulsion 20 %" },
  magnesium: { name: "Magnesium sulfate" }, mannitol: { name: "Mannitol 20 %" }, metoprolol: { name: "Metoprolol" },
  midazolam: { name: "Midazolam" }, milrinone: { name: "Milrinone" }, morphine: { name: "Morphine" },
  naloxone: { name: "Naloxone" }, neostigmine: { name: "Neostigmine" }, nitroglycerin: { name: "Nitroglycerin" },
  n2o: { name: "Nitrous oxide" }, norepinephrine: { name: "Norepinephrine", uk: "Noradrenaline" }, phenylephrine: { name: "Phenylephrine" },
  propofol: { name: "Propofol" }, remifentanil: { name: "Remifentanil" }, rocuronium: { name: "Rocuronium" },
  ropivacaine: { name: "Ropivacaine" }, salbutamol: { name: "Salbutamol (IV/neb)" }, sevoflurane: { name: "Sevoflurane" },
  sodiumBicarbonate: { name: "Sodium bicarbonate 8.4 %" }, succinylcholine: { name: "Succinylcholine" }, sufentanil: { name: "Sufentanil" },
  sugammadex: { name: "Sugammadex" }, thiopental: { name: "Thiopental" }, vasopressin: { name: "Vasopressin" },
  vecuronium: { name: "Vecuronium" },
};

/**
 * Task 26: short screen names for the 7b lung catalogue (the catalogue's full text, with its grading notes, goes in the
 * tooltip). Reviewed with the glossary; an id missing here shows the catalogue text up to its first "(" or " /".
 */
export const LUNG_LABELS: Readonly<Record<string, string>> = {
  ph: 'Pulmonary hypertension', bronchospasm: 'Bronchospasm', asthma: 'Asthma', anaphylaxis: 'Anaphylactic bronchospasm', copd: 'COPD',
  ards: 'ARDS', ild: 'Pulmonary fibrosis', ssc: 'Systemic sclerosis', chestWall: 'Chest-wall restriction', obesity: 'Obesity',
  pneumonia: 'Pneumonia', atelectasis: 'Lobar collapse', pulmOedema: 'Pulmonary oedema', effusion: 'Pleural effusion',
  ptxSimple: 'Pneumothorax', ptxTension: 'Tension pneumothorax', haemothorax: 'Haemothorax', pe: 'Pulmonary embolism',
  fatEmbolism: 'Fat embolism', vae: 'Venous air embolism', aspiration: 'Aspiration', olv: 'One-lung ventilation',
  endobronchial: 'Endobronchial intubation', bpf: 'Bronchopleural fistula', airwayObstruction: 'Tracheal or tube obstruction',
  cf: 'Cystic fibrosis', nmWeakness: 'Neuromuscular weakness', diaphragmParalysis: 'Diaphragmatic paralysis', pregnancy: 'Pregnancy',
  neonatalRds: 'Neonatal RDS', covidPneumonitis: 'Viral pneumonitis', smokeInhalation: 'Smoke inhalation',
};

