// Every v1 rhythm (and the modifier showcases) as gallery strips: id → spec + label + group.
import type { RhythmGroup } from '@pme/engine-core';
import type { StripSpec } from './strip.ts';

export interface CatalogueItem {
  key: string;
  label: string;
  group: RhythmGroup | 'modifier' | 'artefact';
  spec: StripSpec;
}

const r = (key: string, label: string, group: CatalogueItem['group'], spec: StripSpec): CatalogueItem => ({ key, label, group, spec });

export const CATALOGUE: CatalogueItem[] = [
  r('sinus', 'Sinus rhythm', 'sinus', { rhythm: 'sinus' }),
  r('sinusBrady', 'Sinus bradycardia', 'sinus', { rhythm: 'sinusBrady' }),
  r('sinusTachy', 'Sinus tachycardia', 'sinus', { rhythm: 'sinusTachy' }),
  r('sinusArrhythmia', 'Sinus arrhythmia', 'sinus', { rhythm: 'sinusArrhythmia' }),
  r('sinusPause', 'Sinus pause', 'sinus', { rhythm: 'sinusPause', warmupS: 8 }),
  r('atrialTach', 'Atrial tachycardia', 'atrial', { rhythm: 'atrialTach' }),
  r('mat', 'Multifocal atrial tachycardia', 'atrial', { rhythm: 'mat' }),
  r('afib', 'Atrial fibrillation', 'atrial', { rhythm: 'afib' }),
  r('aflutter2', 'Atrial flutter 2:1', 'atrial', { rhythm: 'aflutter', opts: { ratio: 2 } }),
  r('aflutter4', 'Atrial flutter 4:1', 'atrial', { rhythm: 'aflutter', opts: { ratio: 4 } }),
  r('aflutterVar', 'Atrial flutter, variable block', 'atrial', { rhythm: 'aflutter', opts: { ratio: 'variable' } }),
  r('pac', 'Sinus with PACs', 'atrial', { rhythm: 'sinus', mods: { pac: { probability: 0.25 } }, seed: 9 }),
  r('pacAberrant', 'PACs with aberrancy', 'atrial', { rhythm: 'sinus', mods: { pac: { probability: 0.25, aberrant: true } } }),
  r('svtAvnrt', 'SVT (AVNRT)', 'svt', { rhythm: 'svtAvnrt' }),
  r('svtAvrt', 'SVT (orthodromic AVRT)', 'svt', { rhythm: 'svtAvrt' }),
  r('wpwSinus', 'WPW (sinus, delta wave)', 'svt', { rhythm: 'wpwSinus' }),
  r('preexcitedAf', 'Pre-excited AF', 'svt', { rhythm: 'preexcitedAf' }),
  r('junctionalEscape', 'Junctional escape', 'svt', { rhythm: 'junctionalEscape' }),
  r('junctionalAccel', 'Accelerated junctional', 'svt', { rhythm: 'junctionalAccel' }),
  r('junctionalTachy', 'Junctional tachycardia', 'svt', { rhythm: 'junctionalTachy' }),
  r('avb1', '1st-degree AV block', 'avBlock', { rhythm: 'avb1' }),
  r('avb2Mobitz1', '2nd-degree Mobitz I', 'avBlock', { rhythm: 'avb2Mobitz1' }),
  r('avb2Mobitz2', '2nd-degree Mobitz II', 'avBlock', { rhythm: 'avb2Mobitz2' }),
  r('avb2to1', '2:1 AV block', 'avBlock', { rhythm: 'avb2to1' }),
  r('avbHighGrade', 'High-grade AV block (3:1)', 'avBlock', { rhythm: 'avbHighGrade' }),
  r('avb3Narrow', 'CHB, narrow escape', 'avBlock', { rhythm: 'avb3Narrow' }),
  r('avb3Wide', 'CHB, wide escape', 'avBlock', { rhythm: 'avb3Wide' }),
  r('idioventricular', 'Idioventricular rhythm', 'ventricular', { rhythm: 'idioventricular' }),
  r('aivr', 'AIVR', 'ventricular', { rhythm: 'aivr' }),
  r('pvcBigeminy', 'PVC bigeminy', 'ventricular', { rhythm: 'sinus', mods: { pvc: { pattern: 'bigeminy', probability: 0 } } }),
  r('pvcTrigeminy', 'PVC trigeminy', 'ventricular', { rhythm: 'sinus', mods: { pvc: { pattern: 'trigeminy', probability: 0 } } }),
  r('pvcCouplet', 'PVC couplets', 'ventricular', { rhythm: 'sinus', mods: { pvc: { pattern: 'couplet', probability: 0.25 } } }),
  r('pvcMultifocal', 'Multifocal PVCs', 'ventricular', { rhythm: 'sinus', mods: { pvc: { pattern: 'single', probability: 0.3, multifocal: true } }, seed: 9 }),
  r('pvcRonT', 'R-on-T PVCs', 'ventricular', { rhythm: 'sinus', mods: { pvc: { pattern: 'trigeminy', probability: 0, rOnT: true } } }),
  r('vtMono', 'Monomorphic VT', 'ventricular', { rhythm: 'vtMono' }),
  r('vtPoly', 'Polymorphic VT', 'ventricular', { rhythm: 'vtPoly' }),
  r('torsades', 'Torsades de pointes', 'ventricular', { rhythm: 'torsades', mods: { longQT: true } }),
  r('vfCoarse', 'VF (coarse)', 'ventricular', { rhythm: 'vfCoarse', opts: { autoAsystole: false } }),
  r('vfFine', 'VF (fine)', 'ventricular', { rhythm: 'vfFine', opts: { autoAsystole: false } }),
  r('asystole', 'Asystole', 'arrest', { rhythm: 'asystole' }),
  r('pWaveAsystole', 'P-wave asystole', 'arrest', { rhythm: 'pWaveAsystole' }),
  r('agonal', 'Agonal rhythm', 'arrest', { rhythm: 'agonal', warmupS: 2 }),
  r('pea', 'PEA (sinus, pulseless)', 'arrest', { rhythm: 'sinus', opts: { pulseless: true } }),
  r('pacedAAI', 'Paced AAI', 'paced', { rhythm: 'pacedAAI' }),
  r('pacedVVI', 'Paced VVI', 'paced', { rhythm: 'pacedVVI' }),
  r('pacedDDD', 'Paced DDD', 'paced', { rhythm: 'pacedDDD' }),
  r('failureToCapture', 'VVI failure to capture', 'paced', { rhythm: 'pacedVVI', opts: { pacer: { fault: 'failureToCapture', faultRate: 0.5 } } }),
  r('failureToSense', 'VVI failure to sense', 'paced', { rhythm: 'pacedVVI', opts: { atrialRateBpm: 80, pacer: { intrinsic: 'conducted', fault: 'failureToSense', ratePpm: 60 } } }),
  r('oversensing', 'VVI oversensing', 'paced', { rhythm: 'pacedVVI', opts: { pacer: { fault: 'oversensing', faultRate: 0.3 } } }),
  r('tcpCapture', 'Transcutaneous pacing, capture', 'paced', { rhythm: 'asystole', mods: { tcp: { mode: 'fixed', ratePpm: 70, mA: 90, thresholdMa: 70 } } }),
  r('stemiAnterior', 'Anterior STEMI (V1/V3)', 'modifier', { rhythm: 'sinus', mods: { st: { territory: 'anterior', mm: 3 } }, leads: ['V3', 'ecgIII'] }),
  r('stemiInferior', 'Inferior STEMI (II/aVL)', 'modifier', { rhythm: 'sinus', mods: { st: { territory: 'inferior', mm: 3 } }, leads: ['ecgII', 'aVL'] }),
  r('lbbb', 'LBBB', 'modifier', { rhythm: 'sinus', mods: { bbb: 'lbbb' }, leads: ['V1', 'V6'] }),
  r('rbbb', 'RBBB', 'modifier', { rhythm: 'sinus', mods: { bbb: 'rbbb' }, leads: ['V1', 'V6'] }),
  r('hyperK', 'Hyperkalaemia K 7.2', 'modifier', { rhythm: 'sinus', mods: { k: 7.2 } }),
  r('hyperKsine', 'Hyperkalaemia K 8.5 (sine wave)', 'modifier', { rhythm: 'sinus', mods: { k: 8.5 } }),
  r('hypoK', 'Hypokalaemia K 2.5 (U waves)', 'modifier', { rhythm: 'sinus', mods: { k: 2.5 }, leads: ['ecgII', 'V2'] }),
  r('osborn', 'Hypothermia 28 °C (Osborn J)', 'modifier', { rhythm: 'sinusBrady', mods: { tempC: 28 }, leads: ['ecgII', 'V3'] }),
  r('brugada', 'Brugada type 1', 'modifier', { rhythm: 'sinus', mods: { brugada1: true }, leads: ['V1', 'V2'] }),
  r('digoxin', 'Digoxin effect', 'modifier', { rhythm: 'sinus', mods: { digoxin: true } }),
  r('longQT', 'Long QT', 'modifier', { rhythm: 'sinus', mods: { longQT: true } }),
  r('alternans', 'Electrical alternans', 'modifier', { rhythm: 'sinusTachy', mods: { alternans: 0.35, lowVoltage: 0.6 } }),
  r('lvh', 'LVH', 'modifier', { rhythm: 'sinus', mods: { lvh: true }, leads: ['V1', 'V5'] }),
  r('mains', '50 Hz mains interference (diagnostic filter)', 'artefact', { rhythm: 'sinus', mods: { artefact: { mains: 0.3 } }, filter: 'diagnostic' }),
  r('shiver', 'Shivering artefact', 'artefact', { rhythm: 'sinus', mods: { artefact: { shiver: 0.7 } } }),
  r('motion', 'Motion artefact', 'artefact', { rhythm: 'sinus', mods: { artefact: { motion: 0.5 } } }),
  r('cpr', 'VF with CPR artefact', 'artefact', { rhythm: 'vfCoarse', opts: { autoAsystole: false }, mods: { artefact: { cpr: { rateCpm: 110, depth: 0.6 } } } }),
  r('shock', 'Shock artefact (200 J) on VF', 'artefact', { rhythm: 'vfCoarse', opts: { autoAsystole: false }, mods: { artefact: { shock: { atS: 6, energyJ: 200 } } } }),
  r('diathermy', 'Electrosurgery burst', 'artefact', { rhythm: 'sinus', mods: { artefact: { electrosurgery: { atS: 7, durationS: 3 } } } }),
  r('leadOff', 'Leads off (flat, technical)', 'artefact', { rhythm: 'sinus', mods: { artefact: { leadOff: true } } }),
  // Gate 5 coverage additions (executor): one strip for every modifier group the 70 above do not show.
  r('pjc', 'Sinus with PJCs', 'atrial', { rhythm: 'sinus', mods: { pjc: { probability: 0.25 } } }),
  r('failureToPace', 'VVI failure to pace', 'paced', { rhythm: 'pacedVVI', opts: { pacer: { fault: 'failureToPace', faultRate: 0.3 } } }),
  r('tcpNoCapture', 'Transcutaneous pacing, no capture (50 mA < 70 mA threshold)', 'paced', { rhythm: 'asystole', mods: { tcp: { mode: 'fixed', ratePpm: 70, mA: 50, thresholdMa: 70 } } }),
  r('vfEpinephrine', 'VF coarse, 90 s after epinephrine (peak effect)', 'ventricular', { rhythm: 'vfCoarse', opts: { autoAsystole: false }, mods: { epinephrineAtS: 0 }, warmupS: 90 }),
  r('ischaemia', 'Subendocardial ischaemia (ST −0.2 mV, II/V5)', 'modifier', { rhythm: 'sinus', mods: { ischaemicDepressionMv: -0.2 }, leads: ['ecgII', 'V5'] }),
  r('tInversion', 'T-wave inversion', 'modifier', { rhythm: 'sinus', mods: { tInversion: 1 }, leads: ['ecgII', 'V3'] }),
  r('axisLeft', 'Left axis −45° (I/aVF)', 'modifier', { rhythm: 'sinus', mods: { axisDeg: -45 }, leads: ['ecgI', 'aVF'] }),
  r('axisRight', 'Right axis +120° (I/aVF)', 'modifier', { rhythm: 'sinus', mods: { axisDeg: 120 }, leads: ['ecgI', 'aVF'] }),
  r('transitionLate', 'Late precordial transition (V5; V3/V5)', 'modifier', { rhythm: 'sinus', mods: { transitionLead: 5 }, leads: ['V3', 'V5'] }),
  r('lowVoltage', 'Low voltage (×0.5)', 'modifier', { rhythm: 'sinus', mods: { lowVoltage: 0.5 } }),
  r('overrides', 'Interval overrides (PR 280, QRS 140, QT 520 ms)', 'modifier', { rhythm: 'sinus', mods: { overrides: { prMs: 280, qrsMs: 140, qtMs: 520 } } }),
  r('individualityA', 'Individuality: patientSeed 3, variation 1', 'modifier', { rhythm: 'sinus', mods: { patientSeed: 3, morphologyVariation: 1 } }),
  r('individualityB', 'Individuality: patientSeed 4, variation 1', 'modifier', { rhythm: 'sinus', mods: { patientSeed: 4, morphologyVariation: 1 } }),
  r('wander', 'Baseline wander', 'artefact', { rhythm: 'sinus', mods: { artefact: { wander: 1 } }, filter: 'diagnostic' }),
  r('emg', 'EMG (muscle) artefact', 'artefact', { rhythm: 'sinus', mods: { artefact: { emg: 0.7 } } }),
];
